### ISSUE TITLE
Add a character gallery

### ISSUE THREAD

**Issue by gregrobison** [ollama-webui/ollama-webui#112]
I'd like to be able to chat with defined characters like in Oobabooga.

**Comment by tjbck** [comment]
Hi, I will think of ways to implement this feature with #114, Let's continue our discussion there. In the meantime, If you have the system prompt for the characters you want, you can set the system prompt from Settings > General > System Prompts and the model will behave as the character. Thanks!

**Comment by gregrobison** [comment]
Thanks, I think it makes sense. I tested the system prompt and the model responded as expected, so I'm looking forward to saving system prompts as characters.
