### ISSUE TITLE
Parameter Generator

### ISSUE THREAD

**Issue by Phuket2** [ollama-webui/ollama-webui#113]
Some form of setting parameter generator, along the same idea as they have in automatic1111 for  Stable Diffusion. 
eg. With this prompt, generate all variations of answers from temperature 5 to 8 with .2 increments 
You may also allow for the same idea using a selection of the installed models.
 In the crudest form, you could just run the results down the page.  You could also have a dedicated popup window or a result area in the chat with horizontal scrolling that could display the results nicely.
I think this would be a stand-out feature. I haven't used many other chat clients locally, so maybe it's been done already.

**Comment by tjbck** [comment]
Hi, I will think of ways to implement this feature with #114, Let's continue our discussion there. In the meantime, you can also set the temperature by adjusting the temperature slider from Settings > Advanced and the model response will reflect the temperature. Thanks!
