### ISSUE TITLE
Import documents

### ISSUE THREAD

**Issue by pdavis68** [ollama-webui/ollama-webui#117]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A button that allows user to import documents into the conversation, similar to how ChatGPT, Perplexity or Claude do.

**Describe alternatives you've considered**
Turning the documents into text and pasting them, but that's painful.

**Additional context**
Nothing comes to mind.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. Let's continue our discussion on #31.

**Comment by tjbck** [comment]
Duplicate of #31
