### ISSUE TITLE
feat: custom url with chatid for chats

### ISSUE THREAD

**Issue by imaverage** [ollama-webui/ollama-webui#121]
**Describe the solution you'd like**
like chatgpt basically. i want to be able to copy the url for a chat and return to it

**Describe alternatives you've considered**
no alts

**Additional context**

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. This project is currently being overhauled to support #68. Once #123 gets merged to main, I'll think of ways to implement this, including the option to share the conversation with others.

**Comment by tjbck** [comment]
Hi, I've implemented this feature with #123, Please let me know if you encounter any issues. Thanks!
