### ISSUE TITLE
ability to delete specific messages in a thread

### ISSUE THREAD

**Issue by imaverage** [ollama-webui/ollama-webui#122]
**Describe the solution you'd like**
ability to delete specific messages in a thread in a particular chat

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. I'm currently overwhelmed with the amount of work but I'll maybe try to get around to this whenever I can if I decide to implement this feature. If you could elaborate what the use case of this feature could be, or how it could be useful, that will help me with the decision making process. I'll mark as not planned for now, but I will reopen if there are good reasons. Thanks.

**Comment by imaverage** [comment]
A. there is limited context size for these models. often time you have a followup question, but does not need to stay in the chat.
B. if a user names a typo or wants to edit/amend a message, there is no way to do so. allowing selectively deleting a message allows this as well

**Comment by tjbck** [comment]
Hi, There is a way to edit messages you've sent which would address both of your concerns. Are there any other reasons why you would delete a message? Thanks.

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/9c16ecef-28f9-49a7-ba7a-49787b3b020d)
