### ISSUE TITLE
feat: option to toggle generateChatTitle

### ISSUE THREAD

**Issue by xintron** [ollama-webui/ollama-webui#124]
**Is your feature request related to a problem? Please describe.**
Running ollama on low-end hardware causes issues as the UI is issuing a request to generate chat titles, blocking future chats from responding until the title generation has finished. It would be great if the chat title generation could be toggled off for these low-end systems.

**Describe the solution you'd like**
A constant that can be set to false for generateChatTitle: `GENERATE_CHAT_TITLE=false`.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. After #123 gets merged to main, I'll add this option to settings.

**Comment by tjbck** [comment]
Hi, I've included the feature to address this problem with #123, you should have the requested feature with the latest release. Thanks.
