### ISSUE TITLE
$amount bug on mobile

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#127]
On android mobile (any browser), a dollar sign on cost related topics are being escaped so that the result doesnt make sense.

Please see screenshot attached.
![Screenshot_2023-11-22-10-22-09-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ollama-webui/ollama-webui/assets/23272429/a110b5e1-878a-454e-9456-6f40eaf42e82)

**Comment by tjbck** [comment]
Hi, Could you share the raw response with us here? Thanks.

**Comment by tjbck** [comment]
Hi, I've just added a hot fix disabling the latex render for texts starting with '$' sign, I believe that would fix your issue. Please let me know if the problem persists for you. Thanks!
