### ISSUE TITLE
feat: ollama-webui answer notification

### ISSUE THREAD

**Issue by Poulpatine** [ollama-webui/ollama-webui#131]
**Is your feature request related to a problem? Please describe.**
I know that ollama should run on a GPU but it's not always the case.
When I use it, I may have to wait a bit of time before getting an answer.
Hence, an answer notification could be a good way to inform of the response.

**Describe the solution you'd like**
When focus is not on the tab where Ollama webui is running, a notification sent from the browser could remind an answer.

**Describe alternatives you've considered**
Other alternative is to keep the tab opened

**Additional context**
NA

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! Sounds like a great idea, I'll implement this feature in the near future. Stay in tuned!

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/b965e7b1-db86-42b0-9931-de06395f00a3)


The requested feature has been added with #215. Please try out the latest version, and let me know if you encounter any issues. Thanks!

**Comment by coder543** [comment]
iOS supports push notifications on PWAs that have been installed to the Home Screen, but this integration doesn’t seem to be working:

![image](https://github.com/ollama-webui/ollama-webui/assets/726063/a67571b6-e85b-4b77-a570-01430e31755e)

I have not denied the permission.
