### ISSUE TITLE
Install clobbers /etc/systemd/system/ollama.service file destroying any custom configurations like specifying IP or PORT being served or preventing cors errors

### ISSUE THREAD

**Issue by Dougie777** [ollama-webui/ollama-webui#135]
**Describe the bug**

Upgrading to the latest version clobbers my /etc/systemd/system/ollama.service file.  If the file exists it should not be overwritten.  Or the distro should only include a sample file like so /etc/systemd/system/ollama.service.sample

**To Reproduce**

1 Install ollama-webui as a service
2 Customize /etc/systemd/system/ollama.service like adding:
Environment=OLLAMA_HOST=0.0.0.0
Environment=OLLAMA_ORIGINS=*
3 Upgrade to the latest ollama-webui version

**Expected behavior**
/etc/systemd/system/ollama.service is overwritten, destroying any customizations to this file.

**Screenshots**

**Desktop (please complete the following information):**
 ubuntu - but applies to all

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tjbck** [comment]
Hi, Could you tell us how exactly you installed the web ui? The WebUI does not contain any code that edit any system service files. Keep us updated, Thanks!
