### ISSUE TITLE
feat: Upgrade to lockfileVersion 3 in the package-lock.json file

### ISSUE THREAD

**Issue by thesobercoder** [ollama-webui/ollama-webui#137]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to use Bun to install the dependencies because the `lockfileVersion` property is specified as 2 in the `package-lock.json` file.

**Describe the solution you'd like**
The `lockfileVersion` property should be bumped to 3 in the `package-lock.json` file.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. If you could make a PR with the lockfileversion updated to 3 after testing that it works with npm, yarn and bun, I'll review your PR and merge it to main. 

I'll close this issue as not planned for now, as I'm occupied with adding more core features to the product and I'm not entirely sure if bun would be fully compatible with sveltekit projects nor node package dependencies included with this project. Keep me updated, Thanks!
