### ISSUE TITLE
feat: show download progress in notification?

### ISSUE THREAD

**Issue by TheRouce** [ollama-webui/ollama-webui#141]
**Is your feature request related to a problem? Please describe.**
I like to test a lot of models at once and so it's nice to use the webui while I'm waiting for one to download and to be able to see the progress would be helpful.

**Describe the solution you'd like**
Show download progress in a notification rather than in the models tab.

**Describe alternatives you've considered**
A downloads tab, or model list tab on the right hand side.

As additional info, I have been trying to do more with svelte and so if you could point me to where I would work on something like this I would love to contribute.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! Could you clarify what/where you meant by notification? Screenshots or even a wireframe would be extremely helpful. Thanks!

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/f6a29657-afb2-482d-917e-e25433c8ef68)

A feature that would address this issue has been added with https://github.com/ollama-webui/ollama-webui/pull/215. Please try out the latest version, and let me know if you encounter any issues. Thanks!
