### ISSUE TITLE
feat: PWA support

### ISSUE THREAD

**Issue by ntimo** [ollama-webui/ollama-webui#150]
**Is your feature request related to a problem? Please describe.**
Currently the app can't be installed as a PWA which could make it more feel like a native application.

**Describe the solution you'd like**
Make it possible to install the app as an PWA.

**Additional context**
https://blog.logrocket.com/how-to-build-a-progressive-web-app-pwa-with-node-js/

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. I'll take a look at it when I can, as adding core features to the webui is the top priority at the moment. In the meantime, if you manage to implement this feature and make a PR, I'll review and merge to main. Thanks!
