### ISSUE TITLE
OpenAI models second time user input is discarded

### ISSUE THREAD

**Issue by luisherranz** [ollama-webui/ollama-webui#156]
**Describe the bug**

When using OpenAI models, the second user input is discarded and instead, the first input is repeated again. It happens cyclically.

**To Reproduce**

1. Select an OpenAI model, like GPT4-turbo
2. Ask something
3. Check the answer
4. Ask something different
5. The second output is the answer to the first question

**Expected behavior**

The second output should be the answer to the second question.

**Screenshots**

https://github.com/ollama-webui/ollama-webui/assets/3305402/da2972e5-0e02-4725-8fed-5169f83dd20a

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser Chrome 119
 - Version v1.0.0-alpha.11

**Comment by tjbck** [comment]
Hi, Thanks for letting us know! Just merged the branch with the fix. Please try out the latest version and let me know if the issue persists, Keep us updated!

**Comment by luisherranz** [comment]
Working great, thank you 🙂
