### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by mikestaub** [ollama-webui/ollama-webui#169]
I tried running:

docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main

And got this error on my M1 mac:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

the web-ui container still runs fine

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. I'll take a look if there are ways to also provide arm builds using Github Actions. I'll close this for now as you can build the container yourself from your machine which would resolve your issue. In the meantime, if you find a way to provide a build for arm using Github Actions, PR is always welcome. Thanks!
