### ISSUE TITLE
Blank page presented when run as a container (until container is killed)

### ISSUE THREAD

**Issue by cloudxabide** [ollama-webui/ollama-webui#171]
**Describe the bug**
Running ollama-webui as a docker container presents a blank page.  Interestingly enough, as *soon* as I kill the container, the webUI will appear in the browser.  Note:  I am providing an example of running this on a remote host from where my "ollama server" container is running, but the same thing happens when I run ollama-webui on the same node.   I have to use the remote example to remove the possibility of docker networking being the culprit.

**To Reproduce**
1. Run ollama server as a container on Docker on my PC with NVIDIA card (10.10.10.20)
`OLLAMA_ENV_FILE=${HOME}/ollama-env-file.txt
echo "OLLAMA_ORIGINS=\"http://10.10.10.20:*,http://hal9000.matrix.lab:*\"" > $OLLAMA_ENV_FILE
docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --env-file=$OLLAMA_ENV_FILE --name ollama ollama/ollama
`

2. Run Ollama-webui on a separate host (either Ubuntu 22.04 x86 laptop, or MacOS Sonoma M2 laptop)
2.1 MacOS M2
`docker run -it --platform linux/amd64 -d -p 3000:8080 -e OLLAMA_API_BASE_URL=http://10.10.10.20:11434/api --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main`
OR
2.2 Ubuntu x86
`docker run -d -p 3000:8080  --env-file=$OLLAMA_ENV_FILE  --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main`
3. Browse to the endpoint (http://localhost:3000).  Receive a blank page (not connection refused, etc...).  Additionally, I have openen with both Chrome and Safari at the same time.
4. Kill the container running ollama-webu.
5. Instantly the webui will appear (in both browsers when I was testing with both) and is actually functional (i.e. I can update the settings to point to my ollama server endpoint and proceed.
6. I have reviewed the container logs of ollama-webui - and I do not see any errors.  Unfortunately without know what "good" looks like, I also don't know if something is *not* happening that should be.

**Expected behavior**
As I have yet to get this working, I am not entirely certain what to expect.  My guess, however, is that when I browse to my ollama-webui endpoint, that the webui would be presented - and that I would not need to kill the container that was running the webui for it to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browse: Chrome/Safari
 - Version:  Sonoma (I am not sure what "version" we are referring to here)
 
 - OS: Ubuntu
 - Browse: Chrome
 - Version:  22:04 desktop (I am not sure what "version" we are referring to here)

**Additional context**
Happy to execute any testing on my side to help move this along.  Thanks all!

**Comment by tjbck** [comment]
Hi, I cannot seem to reproduce the issue on my side using m1 mac and ubuntu server over LAN. Could you provide us with the browser console logs to better assess what the issue is? Thanks!

**Comment by cloudxabide** [comment]
@tjbck - I am now unable to reproduce, as well.  I made several attempts while testing.  I apologize for taking up your time.
