### ISSUE TITLE
pdf text extraction

### ISSUE THREAD

**Issue by JohnZolton** [ollama-webui/ollama-webui#176]
I want to drag pdfs into the chat window and talk with the ai about them by loading the pdf text into the prompt. I'm trying to implement it myself but have issues with the pdf libraries and svelte/vite. PDFs would already be OCR'd so its just extracting text.

**Comment by DanMyers300** [comment]
I would like this but with the ability to integrate with LangChain. I'm attempting to work on it, if successful I'll make a PR.

**Comment by tjbck** [comment]
Hi, Thanks for the feature request! I'm actively working on a RAG feature for the webui, so stay tuned! Let's continue our discussion here: #31

**Comment by bhaidar** [comment]
Hi @tjbck 
I've uploaded a PDF file (~2mb) and asked the LLAMA3 what is this document about and received "I am not sure ..". Is there a special model to use with documents? Thanks

**Comment by dmvieira** [comment]
Its not working here for me too @bhaidar . I'm trying to summarize a large PDF and it's not working because it's using RAG for PDF text recovery. Why not an option to use all pdf when generate response?

**Comment by thiswillbeyourgithub** [comment]
@dmvieira this might be related to my ongoing PR #5378
