### ISSUE TITLE
"New Chat" created per word streamed, when you click it during message generation.

### ISSUE THREAD

**Issue by leochoo** [ollama-webui/ollama-webui#183]
**Describe the bug**
When you click on "New Chat" while the message is being streamed, "New Chat" will be created per word streamed it seems. 

**To Reproduce**
1. Choose any model and generate a message
2. While generating, Click on 'New Chat'
4. You will see a creation of New Chat, which stop when the answer stream stops.

**Expected behavior**
Message generation stops and the new chat starts.

**Screenshots**
![CleanShot 2023-12-06 at 19 26 35](https://github.com/ollama-webui/ollama-webui/assets/26427048/5c35ae64-ca4c-493f-b506-df52ff1ae8f5)

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Browser  Edge
 - Version 119.0.2151.72 (Official build) (arm64)

**Additional context**
I'm just using frontend. I am NOT using Docker. I am NOT using the backend.
Instead, I'm using the regular ollama previously installed.
I'm running it via `npm run dev` and ollama via `ollama serve`.
Frontend .env points to `OLLAMA_API_BASE_URL='http://127.0.0.1:11434/api'`

**Comment by leochoo** [comment]
It seems that a bunch of `initNewChat` is being called

![CleanShot 2023-12-06 at 19 51 56](https://github.com/ollama-webui/ollama-webui/assets/26427048/534535b9-3921-4f09-a7a6-dcbf0e94281f)
![CleanShot 2023-12-06 at 19 51 50](https://github.com/ollama-webui/ollama-webui/assets/26427048/81a64127-5d61-4fe9-8e4a-51ca813c92b0)

**Comment by tjbck** [comment]
Hi, I just merged the branch with the fix to main, Please let me know if the issue still persists after you try out the latest release. Thanks!
