### ISSUE TITLE
feat: verbose output (show timings per response)

### ISSUE THREAD

**Issue by johncadengo** [ollama-webui/ollama-webui#188]
When running Ollama from the command prompt, you can type the `--verbose` argument to get timings that output like this:

```
$ ollama run --verbose llama2
>>> Hi
Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?

total duration:       1.279118717s
load duration:        891.933µs
prompt eval count:    21 token(s)
prompt eval duration: 231.416ms
prompt eval rate:     90.75 tokens/s
eval count:           25 token(s)
eval duration:        1.042407s
eval rate:            23.98 tokens/s
```

Is there a way to get this to appear in the web UI?

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/49b833ed-40da-43a2-ba85-0e6666860e3e)

The requested feature has been added with #215. Please try out the latest version, and let me know if you encounter any issues. Thanks!

**Comment by johncadengo** [comment]
Ty! 👏 👏 👏

**Comment by johncadengo** [comment]
@tjbck I have just spun up the latest version of this image and so many things have changed. Do you happen to know if this feature is still present? I can't seem to find it in the latest version.

**Comment by tjbck** [comment]
<img width="886" alt="image" src="https://github.com/open-webui/open-webui/assets/25473318/c95022ff-141d-4435-9637-c09bbd366657">


All still there :)

**Comment by johncadengo** [comment]
@tjbck okay, thanks for showing that.

I think what happened between versions for me is that I was decoupling the model API from the docker container and trying to have a separate API for the models. At first, I was using the LiteLLM models feature. I'm assuming it doesn't work for that? 

Anyhow, I figured out how to use Ollama models instead and now I see the generation info again.
