### ISSUE TITLE
403 OPTIONS  "/api/generate"

### ISSUE THREAD

**Issue by Chillance** [ollama-webui/ollama-webui#2]
Hi!

Just tested this and noticed it does a  OPTIONS  "/api/generate" request. From what I can tell this doesn't exist in latest ollama code...

Thoughts?

**Comment by tjbck** [comment]
Hi there,

Browsers often send an OPTIONS request to verify CORS, which might be the case here. Were there any other issues caused by the OPTIONS request?

Thanks.

**Comment by Chillance** [comment]
Well, I get that asking something trying to generate something, but it seems to stop there so nothing else happens.

**Comment by tjbck** [comment]
Could you please provide any specific error messages or logs that you encounter during the process? This information would greatly assist me in diagnosing the problem more accurately and providing you with the appropriate guidance.

Thanks.

**Comment by Chillance** [comment]
How do I get better logs? I tried typing something, pressed enter, and then nothing.

**Comment by tjbck** [comment]
Hi there,

To obtain more detailed logs, you can use the following command for Docker:

```bash
docker logs ollama-webui
```

Additionally, it would be helpful for diagnosing your issue if you could provide a screenshot of your console logs from your browser's developer tools. This will allow us to examine any client-side errors or issues that might not be visible in the server logs.

Please feel free to share the Docker logs and the browser console logs screenshot, and we'll do our best to assist you in resolving the problem.

Thanks.

**Comment by coolaj86** [comment]
@Chillance Part of the reason that browsers invented CORS Preflight Requests (the OPTIONS issue) is to prevent people from stumbling into security issues.

Do you already have the access protected with an API token or HTTP Basic Auth?

Check out https://github.com/jmorganca/ollama/issues/849#issuecomment-1773697189 and the CORS section at https://webinstall.dev/caddy.

**Comment by coolaj86** [comment]
I have an example of how I did it in #10

**Comment by Chillance** [comment]
I don't do anything particular but just staring the ollama serve. And, on the same machine I run this in docker.

`docker run --network=host -p 3000:3000 --name ollama-webui --restart always ollama-webui`

I actually  got chatbot-ollama (other repo) working fine. But here I can see this in the console log:

> 
> e87e0c1f-4d67-4015-959a-0e2b59659483
> 2.fb1b6367.js:52 submitPrompt
> 192.168.1.11/:1 Access to fetch at 'http://192.168.1.11:11434/api/generate' from origin 'http://192.168.1.11:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> start.93b882e2.js:1 
>                 
>        POST http://192.168.1.11:11434/api/generate net::ERR_FAILED
> window.fetch @ start.93b882e2.js:1
> R @ 2.fb1b6367.js:52
> await in R (async)
> re @ 2.fb1b6367.js:58
> start.93b882e2.js:1 
> 
>        Uncaught (in promise) TypeError: Failed to fetch
>     at window.fetch (start.93b882e2.js:1:1402)
>     at R (2.fb1b6367.js:52:108120)

**Comment by Chillance** [comment]
And
`docker logs ollama-webui`
only returns:
`Listening on 0.0.0.0:3000`

**Comment by tjbck** [comment]
Your logs confirm the CORS error as expected, you should pull the latest commit of the main branch and build the docker container. It introduces breaking changes so your command should be replaced with the following instead: 

```sh
docker build --build-arg OLLAMA_API_BASE_URL='' -t ollama-webui .
docker run -d -p 3000:8080 --name ollama-webui --restart always ollama-webui
```

Also make sure to run the following command to serve Ollama, which should solve your issue:

```sh
OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve
```

Thanks.

**Comment by Chillance** [comment]
Thanks! Works now!
