### ISSUE TITLE
feat: For title generation allow to specify a separate model.

### ISSUE THREAD

**Issue by malteneuss** [ollama-webui/ollama-webui#206]
**Is your feature request related to a problem? Please describe.**
The chat title seems to be generated withe the same model that was used in the a chat, which can be unnecessarily slow when chatting with large models like llama2:70B, which takes a lot of resources and time just to summarize a chat.

**Describe the solution you'd like**
Allow to select a separate (e.g. smaller <7B) model to do the summarization for the title (could be set globally) to speed up the title generation. Maybe even autoload/predefine a small model like neural-chat, llama:7B or similar.

**Comment by tjbck** [comment]
Just added with the latest release, please try it out and let me know if you encounter any issues, Thanks!

**Comment by Shadowfita** [comment]
Specifying the auto-generation model seems to default to the current chats model, and ignores (nor saves) my specified model.

**Comment by newptcai** [comment]
Where is this? I could not find it in settings.

**Comment by fivecanal5** [comment]
> Where is this? I could not find it in settings.

looks like the setting has been moved to /admin/settings under Interface
