### ISSUE TITLE
Keep getting server connection failed when starting ollama-webui

### ISSUE THREAD

**Issue by zono50** [ollama-webui/ollama-webui#209]
I run the docker command - docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main

and it starts, i can go to localhost:3000 and it pulls up, but as soon as it does, i get a dropdown at the top saying "Server connection failed" and then won't let me do anything. 

If I go to localhost:11434 it shows ollama is running, and i can run ollama in the terminal, but can't do anything in ollama-webui.

**Comment by tjbck** [comment]
Hi, Could you please provide us with both browser console logs and docker container logs, we cannot diagnose your issue without them. Thanks.

**Comment by zono50** [comment]
Failed to load resource: the server responded with a status of 500 (internal server error) syntax error: unexpected token '<', "<!doctype "... is not valid JSON

The command i run to start the program is - 
 docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe3a0425610>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3a0425610>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/apps/ollama/main.py", line 63, in proxy
    target_response = requests.request(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3a0425610>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO:     172.17.0.1:56854 - "GET /tags HTTP/1.1" 500 Internal Server Error

**Comment by tjbck** [comment]
It seems like Ollama instance is not reachable from the docker container, Could you tell us more about the system you're running Ollama/Ollama WebUI on, as well as how you installed docker on your machine?

**Comment by zono50** [comment]
I installed ollama originally, and it worked fine, but then i installed a program called quivr which i think was trying to run on 3000 as well. I ended up removing that program and reinstalling this one. i'm using linux manjaro

**Comment by tjbck** [comment]
Hmm, strange. Could you try to `curl` ollama from inside the webui container and see if it has access to it? Also, just to make sure both Ollama/Ollama WebUI are running on the same machine, correct? Thanks.

**Comment by zono50** [comment]
yes, if i go to localhost:11434 it says ollama is runninng, and i can run it from my terminal. how do I curl ollama from inside the webui container?

**Comment by tjbck** [comment]
Refer to here: https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell

**Comment by efrancis59** [comment]
Hello, I think I have the same problem : 
- I have the last version of ollama running on a server
- I started ollama-webui using the following command : docker run -d -p 3000:8080 -e OLLAMA_API_BASE_URL=http://myserver.com:11434 --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main
- I installed curl in the container and used it to check access to ollama : curl http://myserver.com:11434
- I got the following message : Ollama is running

In the browser, when I open http://myserver.com:3000, I get the message "Server connection failed".

**Comment by Clovis-krz** [comment]
Same for me, OLLAMA_API_BASE_URL doesnt seem to work when starting docker container. I ended up overwriting the url in the settings on the webui but i have to do that for every computer

**Comment by sartilas** [comment]
same for me and in the UI i have : "Uh-oh! There was an issue connecting to Ollama."

**Comment by zono50** [comment]
I can do the docker exec command but when i get into the contain using /bin/bash, it doesn't recognize any programs like curl, pacman, wget, ping, nothing

**Comment by zono50** [comment]
Got help from the discord, adding this to your docker-compose.yml file should fix it 

 version: '3.6'

services:

  ollama-webui:
    build:
      context: .
      args:
        OLLAMA_API_BASE_URL: '/ollama/api'
      dockerfile: Dockerfile
    image: ollama-webui:latest
    container_name: ollama-webui
    environment:
      - "OLLAMA_API_BASE_URL=http://localhost:11434/api"
      # Uncomment below for WIP: Auth support
      # - "WEBUI_AUTH=TRUE"
      # - "WEBUI_DB_URL=mongodb://root:example@ollama-webui-db:27017/"
      # - "WEBUI_JWT_SECRET_KEY=SECRET_KEY"
    restart: unless-stopped
    network_mode: "host"

volumes:
  ollama: {}

**Comment by tjbck** [comment]
Hi @efrancis59, it looks like you might've made a mistake setting the `OLLAMA_API_BASE_URL` env var, the url should include `/api` at the end. (e.g. `OLLAMA_API_BASE_URL=http://myserver.com:11434/api`)

**Comment by tjbck** [comment]
> Same for me, OLLAMA_API_BASE_URL doesnt seem to work when starting docker container. I ended up overwriting the url in the settings on the webui but i have to do that for every computer

@Clovis-krz Could you also provide us with which command you used to install, as well as the ollama setup you have? Thanks.

**Comment by tjbck** [comment]
> same for me and in the UI i have : "Uh-oh! There was an issue connecting to Ollama." curl ollama from inside the webui container : "root@41938ad91712:/app/backend# curl http://localhost:11434/ curl: (7) Failed to connect to localhost port 11434: Connection refused"
> 
> But in in the host : "Ollama is running"

@sartilas, Please refer to here: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach


Also, if you could provide us with the setup you have, it would help us tremendously.

**Comment by tjbck** [comment]
Here are some potential solutions I found by googling:

- https://stackoverflow.com/questions/75237114/max-retries-exceeded-with-url-failed-to-establish-a-new-connection-errno-111

- https://forums.docker.com/t/genai-stack-connection-error-with-host-docker-internal-port-11434/137993/2

**Comment by zono50** [comment]
i previously updated my version of ollama but still didn't fix the issue, so i stopped 11434 process and ollama, removed ollama-webui, and then did git clone, and ran docker compose up -d --build. It fixed my issuue, and am back on port 3000 enjoying the good life

**Comment by iamyb** [comment]
same here. the api request to http://localhost:3000/ollama/api/tags was failed with Bad Request reported. api request http://localhost:3000/api/v1/ is OK.

**Comment by iamyb** [comment]
> same here. the api request to http://localhost:3000/ollama/api/tags was failed with Bad Request reported. api request http://localhost:3000/api/v1/ is OK.

work out with below. 
`docker run -d --network=host -e OLLAMA_API_BASE_URL=http://localhost:11434/api --name ollama-webui --restart always ollama-webui`

**Comment by djmaze** [comment]
AFAICS, setting the `OLLAMA_API_BASE_URL` env var on the prebuilt docker container cannot work because the default url seems baked in to the frontend html during the build process.

The way the build currently works here, you have to build your own docker image with ` --build-arg OLLAMA_API_BASE_URL=http://your-server.com:11434/api` and then use that.

This is a design fault and needs to be fixed.

**Comment by tjbck** [comment]
Hi @djmaze, FYI It's **not** a design fault and it working at it should, By registering the `OLLAMA_API_BASE_URL` env var in the docker container, you essentially create a backend reverse proxy link, redirecting hardcoded `[your webui url]/ollama/api` route to `[your ollama url]/api`. Please refer to here: https://github.com/ollama-webui/ollama-webui#project-components. Thanks.

**Comment by djmaze** [comment]
Oh, well, sorry, then I got that wrong.

As I had the same error message here is a snippet of my docker logs with the original setup. I see the following error:

```
INFO:     10.0.1.5:37178 - "GET /tags HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 109, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 134, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 265, in stream_response
    await send({"type": "http.response.body", "body": chunk, "more_body": True})
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 560, in send
    raise RuntimeError("Response content longer than Content-Length")
RuntimeError: Response content longer than Content-Length
```

Not sure why this happens. Maybe there is a problem with https urls (my ollama is available via https)?

**Comment by tjbck** [comment]
@djmaze Could you provide us with the commands you used to install? Also, is Ollama running on the same server as Ollama WebUI?

**Comment by djmaze** [comment]
It's different docker containers on the same machine. For Ollama WebUI, I used the original docker image and command from the documentation (replaced my domain with `example.com` in the snippets):

```bash
docker run -d -p 3000:8080 -e OLLAMA_API_BASE_URL=https://ollama.example.com/api --name ollama-webui ghcr.io/ollama-webui/ollama-webui:main
```

I just realized the logs now don't show the error anymore, only this:

```
INFO:     172.17.0.1:59804 - "GET /tags HTTP/1.1" 400 Bad Request
```

When calling `https://webui.example.com/api/tags` manually, the page shows the following error message:

```
{"detail":"Server Connection Error","message":"404 Client Error: Not Found for url: https://ollama.example.com/api/tags"}
```

And I don't see any access attempts in the Ollama server log, so the proxy connection seems not being established at all.

(Getting the url via `curl` from within the webui container works, btw.)

**Comment by tjbck** [comment]
@djmaze If you can join our Discord server and send me a pm with your ollama url, I'll personally take a look. Thanks.

**Comment by JereHub77** [comment]
I'm having the same problem, Ollama Webui running in docker can't call Ollama API running on localhost (standard port 11434), Ollama API respond correctly (I've tried using curl), I tried to set the OLLAMA API_BASE_URL variable with http://localhost:11434/api but it doesn't work.

**Comment by m-hoseyny** [comment]
hello,
I just joined the Discord server and asked about the problem. However, I didn't get any response. How can I solve this problem?

**Comment by themw123** [comment]
same for me. Docker logs shows: 
`INFO:     100.79.239.85:1866 - "GET /ollama/api/version HTTP/1.1" 500 Internal Server Error`
And in browser console i see its not able to call version and tags endpoint (500)

**Comment by welchste** [comment]
I keep getting this as well. Not using any containers, everything manually installed
```
INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
get_all_models
INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
get_all_models
INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
get_all_models
INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
```

**Comment by targinosilveira** [comment]
> I keep getting this as well. Not using any containers, everything manually installed
> 
> ```
> INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
> get_all_models
> INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
> get_all_models
> INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
> get_all_models
> INFO:     127.0.0.1:47524 - "POST /ollama/urls/update HTTP/1.1" 500 Internal Server Error
> ```

I am gatting the same problem, ollama and open webui was installed manualy in a VM, when I run directly on ollama or a CLI client I haven't problems, only when I try by Open WebUI 

INFO:     127.0.0.1:47270 - "POST /ollama/api/chat HTTP/1.1" 500 Internal Server Error
http://localhost:11434
INFO:     127.0.0.1:47270 - "POST /ollama/api/generate HTTP/1.1" 500 Internal Server Error

**Comment by justinh-rahb** [comment]
@welchste  @targinosilveira 

If you've installed directly, check your `.env` file against the `.env.example` file and be sure you've updated your variable names. `OLLAMA_API_BASE_URL` -> `OLLAMA_BASE_URL`

**Comment by welchste** [comment]
> @welchste @targinosilveira
> 
> If you've installed directly, check your `.env` file against the `.env.example` file and be sure you've updated your variable names. `OLLAMA_API_BASE_URL` -> `OLLAMA_BASE_URL`

Hey, I tried that. Then actually went Docker route, with no luck. Then I used the local host option with docker and still no luck. I then installed Ollama on a remote server, with no luck.

Finally I tried a different Front End project, and that works. So at least I ruled out any firewall or Ollama specific issues. 

This other project is a place holder so look forward to being able to use Open-WebUI in the future.

**Comment by justinh-rahb** [comment]
> > @welchste @targinosilveira
> > If you've installed directly, check your `.env` file against the `.env.example` file and be sure you've updated your variable names. `OLLAMA_API_BASE_URL` -> `OLLAMA_BASE_URL`
> 
> Hey, I tried that. Then actually went Docker route, with no luck. Then I used the local host option with docker and still no luck. I then installed Ollama on a remote server, with no luck.
> 
> Finally I tried a different Front End project, and that works. So at least I ruled out any firewall or Ollama specific issues.
> 
> This other project is a place holder so look forward to being able to use Open-WebUI in the future.

Mind me asking, what had you set your `OLLAMA_BASE_URL` to through these attempts?

**Comment by welchste** [comment]
> > > @welchste @targinosilveira
> > > If you've installed directly, check your `.env` file against the `.env.example` file and be sure you've updated your variable names. `OLLAMA_API_BASE_URL` -> `OLLAMA_BASE_URL`
> > 
> > 
> > Hey, I tried that. Then actually went Docker route, with no luck. Then I used the local host option with docker and still no luck. I then installed Ollama on a remote server, with no luck.
> > Finally I tried a different Front End project, and that works. So at least I ruled out any firewall or Ollama specific issues.
> > This other project is a place holder so look forward to being able to use Open-WebUI in the future.
> 
> Mind me asking, what had you set your `OLLAMA_BASE_URL` to through these attempts?

Hey @justinh-rahb  wanted to close this loop. It was user error, where I kept adding the port and `/api` URI was in the UI. The base ollama URL I was not including the port. Tried again today put `OLLAMA_BASE_URL=IP.V.4.Adress:11434` and that did the trick

**Comment by ilhooq** [comment]
I am facing the same problem. By default, Ollama only listens to the local IP address 127.0.0.1, which means that the network inside the Docker container cannot bind to the host port 11434.

To resolve this issue, you can follow these steps:

1. Open the ollama unit file located at `/etc/systemd/system/ollama.service`.
2. In the [Service] section of the file, add the following line: `Environment="OLLAMA_HOST=0.0.0.0"`.
3. Reload systemctl `sudo systemctl daemon-reload`
4. Restart the service   `sudo systemctl restart ollama.service`

This configuration change will allow Ollama to listen on all available network interfaces, including the external IP address (0.0.0.0).

You can find more detailed information this issue discussion: https://github.com/ollama/ollama/issues/2603.

**Comment by justinh-rahb** [comment]
> I am facing the same problem. By default, Ollama only listens to the local IP address 127.0.0.1, which means that the network inside the Docker container cannot bind to the host port 11434.
> 
> To resolve this issue, you can follow these steps:
> 
> 1. Open the ollama unit file located at `/etc/systemd/system/ollama.service`.
> 2. In the [Service] section of the file, add the following line: `Environment="OLLAMA_HOST=0.0.0.0"`.
> 3. Reload systemctl `sudo systemctl daemon-reload`
> 4. Restart the service   `sudo systemctl restart ollama.service`
> 
> This configuration change will allow Ollama to listen on all available network interfaces, including the external IP address (0.0.0.0).
> 
> You can find more detailed information this issue discussion: [ollama/ollama#2603](https://github.com/ollama/ollama/issues/2603).

It is **NOT** recommended to edit `.service` files directly, you should use a local override by doing `systemctl edit ollama.service` instead.

**Comment by methodtrades** [comment]
For me and anyone else experiencing the 500 internal server error on POST to ollama - it was because I had my context window settings too high, since I was using a higher one for openai.

Maybe there should be separate settings like this depending on what model you are using?

**Comment by robin536180** [comment]
> Admin Panel -> Connections -> Changing Ollama API from http://localhost:11434 to http://host.docker.internal:11434 worked for me.

That's the final answer, and it works!

**Comment by Bodo-von-Greif** [comment]
> OLLAMA_HOST=0.0.0.0:11434 ollama serve this works!

My installation which worked without problems broke when i switched to systemd installation of Ollama.
This hint saved my configuration and BTW i also included HTTP_PROXY and HTTPS_PROXY and NO_PROXY.
Thanks a lot!

**Comment by justinh-rahb** [comment]
@Bodo-von-Greif OLLAMA_HOST is covered by their FAQ:
https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux

**Comment by ipipe-hellis** [comment]
> Admin Panel -> Connections -> Changing Ollama API from http://localhost:11434 to http://host.docker.internal:11434 worked for me.

This also worked for me.

**Comment by prachetas** [comment]
If you have installed ollama on windows then: 
open command prompt  and write: ipconfig
then take the IPV4 address and add it to Admin Panel -> Connections -> e.g. http://192.XXX.XXX.XXX:11434

**Comment by ibinasaker** [comment]
For me the flag "--add-host=host.docker.internal:host-gateway" was the answer, note that this command will let the container gateway to the host network. a bit risky in enterprise/prod environments.

whole command for me was:

sudo docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

**Comment by mjhumphrey4** [comment]
I used the following fix:

* Allow Ollama to listen for connections on all interfaces, not just `127.0.0.1`. This is because `host.docker.internal:host-gateway` will use the public facing interface on your host. Allowing Ollama to accept connections from all interfaces enables Docker to access Ollama on your host. As a result, if you try accessing `curl host.docker.internal:11434/api` in the Open WebUI Docker container environment, you will not get a result, but after allow Ollama to listen for connections on all interfaces, you will receive `Ollama is running`. Below are some test logs

```
<-- Enter the Open WebUI to test access to the Ollama Port 11434 -->

$ sudo docker exec -it open-webui /bin/bash
root@704ff21e6d24:/app/backend# curl host.docker.internal:11434 
curl: (7) Failed to connect to host.docker.internal port 11434 after 0 ms: Couldn't connect to server

<-- Edit Ollama to allow connections to all interfaces -->
$ sudo systemctl edit ollama.service
[Service]
Environment="OLLAMA_HOST=0.0.0.0"
$ sudo systemctl restart ollama.service
$ sudo docker exec -it open-webui /bin/bash
root@704ff21e6d24:/app/backend# curl host.docker.internal:11434/api
root@704ff21e6d24:/app/backend# curl host.docker.internal:11434
Ollama is runningroot@704ff21e6d24:/app/backend# 
```

Refresh your Open WebUI interface and verify that you can access Ollama well. You can safely deploy Open WebUI using any of the official installation commands such as: `sudo docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main`

> Don't forget to allow the port through your firewall config.
