### ISSUE TITLE
speech cann't be chinese

### ISSUE THREAD

**Issue by bennyyu79** [ollama-webui/ollama-webui#217]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mak448a** [comment]
Please include more information. Does this mean that it's responding in chinese?

**Comment by tjbck** [comment]
Hi, Please create an issue with more context, Thanks. Closed for insufficient context.
