### ISSUE TITLE
Persist chat history while running on Docker

### ISSUE THREAD

**Issue by seth100** [ollama-webui/ollama-webui#218]
**Describe the bug**
I'm running the [Docker Compose stack](https://github.com/ollama-webui/ollama-webui/blob/main/docker-compose.yml) of this great UI and I see that the chat history is not kept if I remove browser data.
Is there a way to keep it on the system storage, e.g. using Docker volumes to persist some folder where they are stored?

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox 120

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. This feature will be added once #216 gets merged to main. Stay tuned! Duplicate of #68

**Comment by seth100** [comment]
Thanks
