### ISSUE TITLE
Support for llava (multimodal)

### ISSUE THREAD

**Issue by gmaijoe** [ollama-webui/ollama-webui#220]
**Is your feature request related to a problem? Please describe.**
Would love support for multimodal on UI: see https://twitter.com/jmorgan/status/1735095334601216010

**Describe the solution you'd like**
Drag and drop for images and upload arbitrary files

**Describe alternatives you've considered**
n/a

**Additional context**
would be an excellent open source feature to be competitive with chat gpt and other SOTA inference applications

**Comment by tjbck** [comment]
It's already been added yesterday! Update to the latest version and try it out! Thanks!
