### ISSUE TITLE
feat: enable concurrent model downloads

### ISSUE THREAD

**Issue by gmaijoe** [ollama-webui/ollama-webui#221]
**Describe the bug**
Right now I can download multiple models at the same time and end up seeing sha hashes collisions in the UI.

**To Reproduce**
You can just type in 2 different models and import at the same time

**Expected behavior**
parallel model imports should show up on different lines along with a label of the model name + download progress bars for each

**Screenshots**
<img width="643" alt="Screenshot 2023-12-14 at 5 39 01 PM" src="https://github.com/ollama-webui/ollama-webui/assets/7184919/48f3e468-5abf-48c3-b5ca-861a5fd6735e">

**Desktop (please complete the following information):**
 - OS: Mac M1
 - Browser Brave

**Additional context**
N/A

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. I'll take a look in the near future and assess it's usability/feasibility. Thanks!

**Comment by anuraagdjain** [comment]
A sneak peak of parallel downloading of the models. 

https://github.com/ollama-webui/ollama-webui/assets/4705103/c4377b83-6300-4297-957f-be0137ee955e

**Comment by anuraagdjain** [comment]
Can one of you confirm if the progress bar is never visible when the UI is light mode?

**Comment by tjbck** [comment]
> Can one of you confirm if the progress bar is never visible when the UI is light mode?

Yep, just noticed yesterday and should've been fixed with the latest release!
