### ISSUE TITLE
Import Model Dropdown

### ISSUE THREAD

**Issue by gmaijoe** [ollama-webui/ollama-webui#222]
**Is your feature request related to a problem? Please describe.**
Right now, the flow for importing models requires going to https://ollama.ai/library. It would be nice to have these models pulled via API so a user doesn't need to have 2 tabs open.

**Describe the solution you'd like**
1. Auto pull models from ollama.ai/library via API. Can probably use newest or most popular by default.
2. Maybe select model can also have a UI that displays https://ollama.ai/library as an iFrame OR recreate it with more stats could be cool so I can just select locally.

**Describe alternatives you've considered**
No alternatives, just have 2 tabs open

**Additional context**
n/a

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. I'll close this issue for now because afaik there aren't any API endpoints listing all available models from Ollama.ai. However, if you find a way to get the list of available models from the website, feel free to make a PR. Thanks!
