### ISSUE TITLE
BUG: "POST /chat HTTP/1.1" 400 Bad Request

### ISSUE THREAD

**Issue by mak448a** [ollama-webui/ollama-webui#224]
**Describe the bug**
When I try to send a message to the model, it gives this error: `"POST /chat HTTP/1.1" 400 Bad Request`. The webui also gives this error: `Uh-oh! There was an issue connecting to Ollama.` It generates the title of the chat fine though.

**To Reproduce**
1. Send a message through the ui and look through the logs

**Desktop (please complete the following information):**
 - OS: Fedora Linux 39 KDE Spin
 - Browser Firefox

**Comment by tjbck** [comment]
Hi, Could you verify that you're on the latest version of Ollama? Thanks.

**Comment by mak448a** [comment]
Oh, I'm on ollama version 0.1.10

**Comment by mak448a** [comment]
I'll update and close if it's gone

**Comment by mak448a** [comment]
It's gone!
