### ISSUE TITLE
What happens if I press the thumbs up button?

### ISSUE THREAD

**Issue by mak448a** [ollama-webui/ollama-webui#225]
I'd like to know who it gets sent to. Thanks!

**Comment by tjbck** [comment]
Hi, it does not get sent to anybody unless you decide to share you chat log with others, and all of your data is saved on your local browser. Thanks!

**Comment by tdiprima** [comment]
@tjbck I'm glad it doesn't get sent to anybody.  Question, though: What is it used for, locally?  Is there some kind of  reinforcement learning from human feedback going on in the background?  Could you please explain what happens when you click thumbs up?
