### ISSUE TITLE
Document WEBUI_DB_URL / WEBUI_AUTH

### ISSUE THREAD

**Issue by khromov** [ollama-webui/ollama-webui#228]
**Is your feature request related to a problem? Please describe.**
I would like to understand how WEBUI_DB_URL / WEBUI_AUTH works. Even though I configured a MongoDB instance and set the mentioned variables I don't see anything changing in the admin. I would assume that some sort of login system would activate based on code like this, so there must be something I am missing:

https://github.com/ollama-webui/ollama-webui/blob/0820d846190569334151d2970169f77240a0916d/backend/apps/ollama/main.py#L35

**Describe the solution you'd like**
Creat documentation.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tjbck** [comment]
Hi, Those env vars were for WIP feature, and will be deprecated and replaced with an embeddable db in #216. Thanks.
