### ISSUE TITLE
doc: Authorization settings documentation

### ISSUE THREAD

**Issue by khromov** [ollama-webui/ollama-webui#229]
**Is your feature request related to a problem? Please describe.**
It's unclear what Authorization under Settings > Authentication does. Is this for sending an Authorization to the Ollama server?

**Describe the solution you'd like**
Add documentation.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tjbck** [comment]
Hi! With #216, Authorization header feature will be deprecated and user system will be implemented in lieu of the existing Authorization settings, Stay tuned!

**Comment by tjbck** [comment]
Hi, Just merged #216 to main! When upgrading make sure to add `-v ollama-webui:/app/backend/data` flag to the docker command. Feel free to reach out if you encounter any issues or have questions, Thanks!
