### ISSUE TITLE
feat: multiple draft generations and rlhf data collection

### ISSUE THREAD

**Issue by nivibilla** [ollama-webui/ollama-webui#231]
**Is your feature request related to a problem? Please describe.**
Recent DPO models being so good shows the impact of having good rlhf datasets.

**Describe the solution you'd like**

Similar to lymsys's arena battle. The ability to make multiple draft generations per prompt generations (from the same model, or different models/endpoints) and then the user would be able to click which one is better(possibly even edit the answer and fix). This would provide very rich and useful conversation trees along with rlhf data.

**Describe alternatives you've considered**
Lymsys ui kind of does this. With the battle mode but limited to one prompt, no follow up. I was looking for the ability to make multiple drafts every turn in the conversation.

**Comment by tjbck** [comment]
Hi, I'm not sure if I understand what your feature request, could you elaborate a bit more? You can regenerate the responses and pick the one you like the most to continue the conversation if that's the feature you're requesting. Thanks.

**Comment by nivibilla** [comment]
Hi, yeah sorry im not explaining properly. 

In addition to be able to generate multiple drafts like you have already. I would like a way to keep record of that data. As in be able to export human preference data for prompt response based on which one is better. (I see you already have a thumbs up button but not sure where this data is recorded)

**Comment by tjbck** [comment]
You can export all the chat logs if thats the feature you're looking for!

**Comment by nivibilla** [comment]
Does that include if multiple generations were made for the same prompt and the thumbs up flag?

**Comment by tjbck** [comment]
Yep! It should have everything, let me know if it doesn't, I'll reopen this issue. Thanks!

**Comment by briancleland** [comment]
Hi @tjbck , can you point me to where the thumbs-up/thumbs-down is recorded in the exported json please?

**Comment by tjbck** [comment]
@briancleland, I'd suggest you wait for #216 to get merged to main. I think there might've been a bug with the message rating annotation feature. Stay tuned!

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/bdece95a-bf0e-4b0d-9cc4-d37dfc5d1dc4)

**Comment by briancleland** [comment]
Perfect, thanks!
