### ISSUE TITLE
feat: UI to download gguf models from huggingface and use it model files

### ISSUE THREAD

**Issue by kavinask007** [ollama-webui/ollama-webui#234]
Modelfile interface is currently limited to using only models officially provided by Ollama  .
Providing a UI interface to browse huggingface for GGUF models , selecting and downloading them by clicking buttons  and able to use them in modelfiles would be great 

Ollama web server does support local files 
https://github.com/jmorganca/ollama/tree/main?tab=readme-ov-file#import-from-gguf

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. I've actually been thinking of ways to implement this feature for a while now, I'll get around to it when I can, stay tuned!

**Comment by tjbck** [comment]
Hi! I've been actively working on this feature, and intuitively showing huggingface files on the webui seems tricker than I thought :/ As an alternative, I'll be adding a feature where users can download the gguf files themselves and then upload it to the webui. Stay tuned!

**Comment by Nodael** [comment]
No news on this feauture ?

**Comment by cleanunicorn** [comment]
> No news on this feauture ?

It's marked as complete. You can find it in the models tab, in settings.
