### ISSUE TITLE
why response message looks like json? is this correct?

### ISSUE THREAD

**Issue by teamsmiley** [ollama-webui/ollama-webui#237]
<img width="722" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/4934139/0d3e3754-ba63-457d-8665-001253e0666a">

**Comment by tjbck** [comment]
Hi, we cannot give you a definitive answer as the responses depend on the model/param settings you use, if you're only getting a json formatted responses, make sure to check if the request mode has been set to default in the "advanced" settings. Thanks!

**Comment by teamsmiley** [comment]
<img width="677" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/4934139/0c99feb0-8baf-4374-8c26-5f1e3838c8d8">


great..

thank you so much
