### ISSUE TITLE
Modelfiles have disappeared, but still accessible in the model selection dropdown

### ISSUE THREAD

**Issue by HenryHolloway** [ollama-webui/ollama-webui#239]
**Describe the bug**

**To Reproduce**
1. install ollama-webui with docker on ubuntu 23.10
2. Download a model (this occured with dolphin2.1-mistral and dolphin-mixtral, but I suspect that isn't the issue)
3. Create a new model file with the downloaded model
4. New modelfile works great
5. ??? Go to sleep? Restart the container? I'm honestly not sure
6. Modelfiles will no longer be in the "Modelfiles" tab under "My Modelfiles", but it will still be accessible when selecting a model. When talking to the modelfile, behavior is as expected, except the profile image for that modelfile is gone.

**Expected behavior**
Modelfiles persist as normal

**Screenshots**
![image](https://github.com/ollama-webui/ollama-webui/assets/33534238/119ba980-571e-449c-8fd5-a3be886711cf)
![image](https://github.com/ollama-webui/ollama-webui/assets/33534238/8d3232b6-e0fe-49e6-80c7-c28052e4c2c5)
![image](https://github.com/ollama-webui/ollama-webui/assets/33534238/0ef14aa2-d618-4225-a31e-484df6f02353)
Works as expected...

**Comment by tjbck** [comment]
Hi, Were you accessing the webui from a different browser or in a incognito mode? The modelfiles only get saved to the browser as of now, so if your cache gets cleared on the browser side, they will get removed. I'll close this issue for now but stay tuned for #216. Thanks!
