### ISSUE TITLE
What happened to authentication?

### ISSUE THREAD

**Issue by m0wer** [ollama-webui/ollama-webui#240]
A few days ago there was a way of having multiple user support with authentication with the WIP comments on the docker-compose. This commnets have been removed (#219) and authentication no longer works (even with the old compose with uncommented WIP stuff).

What happened? What's the plan?

**Comment by tjbck** [comment]
Hi, We've removed the WIP codes as we will be refactoring and redesign the whole backend architecture to have the DB embedded so that there isn't no need for a separate mongoDB instance. #216 will enable full support for multiple user feature w/ authentication, Stay tuned!

**Comment by m0wer** [comment]
Great! Thanks for the explanation.
