### ISSUE TITLE
BUG: Ollama does not report correct version properly, so ollama-webui errors when loading the interface

### ISSUE THREAD

**Issue by sjclayton** [ollama-webui/ollama-webui#263]
**Describe the bug** 

When I open the web UI, I am greeted with this error message `Connection Issue or Update Needed` followed by `Oops! It seems like your Ollama needs a little attention.
We've detected either a connection hiccup or observed that you're using an older version. Ensure you're on the latest Ollama version
(version 0.1.16 or higher) or check your connection.` If I close this pop-up, everything works normally.

Running a test connection to `http://127.0.0.1:11434/api/version` reports `0.0.0`

It would appear that Ollama does not actually report the current version as of this time through the API, also I get the same result from running `ollama --version` on the command line.

**To Reproduce** 
 
     1. Open the Web UI in browser.
     
## Environment

     * OS: Arch Linux
     * Browser: Firefox 121
     * Ollama Version 0.1.17

**Comment by tjbck** [comment]
Hi! Could you tell us more about your installation method that was required in the form? Thanks!

**Comment by sjclayton** [comment]
I am running the Web-UI only through Docker, Ollama is installed via Pacman.

Yes, the issue might be theirs... but from what I can tell they have never reported any version but 0.0.0 through that API call... so having the Web-UI check for something that it won't get seems like an issue.

**Comment by tjbck** [comment]
Hi, The desktop/docker version of Ollama include the api route that functions properly, so maybe pacman might be the culprit here? Could you try installing Ollama using other installation methods? Thanks!

**Comment by melanopsis** [comment]
I can confirm that this is a packaging issue on Arch. The webui works fine if I pull and run the ollama docker image.

**Comment by anuraagdjain** [comment]
Same issue with home-brew on Mac. Had to uninstall the home-brew version and install the app from the official website.

**Comment by nerdenough** [comment]
Same issue when cloning Ollama manually and building Ollama's Dockerfile. Can be worked around by replacing `0.0.0` with an actual version number is `ollama/version/version.go` and rebuilding.

**Comment by tjbck** [comment]
Seems like we might have to create this issue on the Ollama GitHub repo as well. If anyone creates one, please link this issue!

**Comment by sjclayton** [comment]
> I can confirm that this is a packaging issue on Arch. The webui works fine if I pull and run the ollama docker image.

Same here, have it running fine now using the docker image for ollama with the web-ui also running in docker.

**Comment by tjbck** [comment]
I'll close this issue for now, but if anyone wants to create an issue on Ollama repo, feel free to link this issue! Thanks!

**Comment by ThatOneCalculator** [comment]
Can `0.0.0` be whitelisted as a version?

**Comment by tjbck** [comment]
@ThatOneCalculator, will try to whitelist w/ #216, Stay tuned!

**Comment by ThatOneCalculator** [comment]
Awesome, thank you!
