### ISSUE TITLE
Request response from ollama not updating in UI

### ISSUE THREAD

**Issue by trustraptor** [ollama-webui/ollama-webui#264]
# Bug Report

## Description
Looks as if its loading / waiting indefinitely for response from ollama. I created the docker containers for hassle-free installation as recommended in readme. 
i can run inference directly in ollama docker image, or through curl to the api endpoint
`docker ps -a` results
   ollama-webui:latest    "sh start.sh"          0.0.0.0:3000->8080/tcp, :::3000->8080/tcp       ollama-webui
   ollama/ollama:latest   "/bin/ollama serve"   0.0.0.0:11434->11434/tcp, :::11434->11434/tcp   ollama
Also, saved OLLAMA_HOST=0.0.0.0 and OLLAMA_ORIGINS=* to env variable in docker

**Steps to Reproduce:**
1. Modify compose yml for GPU support and Exposing Ollama API 
4.  `docker compose up -d --build`
5. go to localhost:3000/

**Expected Behavior:**
add model and chat

**Actual Behavior:**

1. UI loads
2. Cannot add model from settings
3. sends my input and processed by ollama docker (can confirm from system monitor)
6. Infinite loading response

## Environment

- **Operating System:** Ubuntu 22.04.3
-  **Browser Firefox

## Reproduction Details

**Confirmation:**
- [ X] I have read and followed all the instructions provided in the README.md.
- [ X] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
![Screenshot from 2023-12-22 17-29-28](https://github.com/ollama-webui/ollama-webui/assets/35881846/a733292f-e84d-436f-af08-de130fdc2904)

## Installation Method
build both ollama and webui docker images with docker compose up

## Additional Information
not sure where else to start for troubleshooting, im not familiar with .ts / svelte. I'm wondering if its the format of the json request / response expected. Where is that in the code?

**Comment by tjbck** [comment]
Hi! We're going to have to see the browser console logs, please share them with us! Thanks!

**Comment by trustraptor** [comment]
> Hi! We're going to have to see the browser console logs, please share them with us! Thanks!

from Firefox console log:
Uncaught (in promise) ReferenceError: TextDecoderStream is not defined
    Immutable 41
    <anonymous> http://localhost:3000/:43
    promise callback* http://localhost:3000/:42
3.7ccbfcc4.js:1:7292
    W Immutable
    AsyncFunctionThrow self-hosted:672
    Immutable 20
    InterpretGeneratorResume self-hosted:1458
    AsyncFunctionNext self-hosted:668
    (Async: async)
    v Immutable
    map self-hosted:180
    Immutable 6
    InterpretGeneratorResume self-hosted:1458
    AsyncFunctionNext self-hosted:668
    (Async: async)
    v Immutable
    map self-hosted:180
    Immutable 6
    AsyncFunctionNext self-hosted:668
    Immutable 3
    <anonymous> http://localhost:3000/:43
    (Async: promise callback)
    <anonymous> http://localhost:3000/:42

**Comment by tjbck** [comment]
Hmm, first time seeing that error. Maybe you're using an outdated version of firefox? I cannot seem to reproduce the issue on my ubuntu machine with firefox. If you could provide more details on how to reproduce the issue, that would be extremely helpful. Thanks!

**Comment by trustraptor** [comment]
Yes I updated the browser, it's working. Thanks, I feel dumb now!

**Comment by themw123** [comment]
I am also facing this issue but just with chatgpt. I am using Chrome 120.0.6099.130. On firefox everything works fine. I am using latest olama and latest ghcr.io/ollama-webui/ollama-webui:main , both from docker.

**Comment by tjbck** [comment]
Hi @themw123, Thanks for reporting the issue! Please try out the latest release, It should fix your issue. Let me know if the issue still persists, Thanks!

**Comment by themw123** [comment]
big thank @tjbck , it's working again!
