### ISSUE TITLE
Use Tailwindcss-typography to assist with markdown styling

### ISSUE THREAD

**Issue by SethBurkart123** [ollama-webui/ollama-webui#27]
#### Summary:

The application successfully renders Markdown into HTML elements, but lacks any styling for them. For example, `#` headings are converted to `<h1>` elements but appear unstyled.

#### Suggested Solution:

To resolve this, consider integrating the [@tailwindcss/typography](https://tailwindcss.com/docs/typography-plugin) plugin, which is fully compatible with the already-implemented Tailwind CSS framework. This plugin will provide out-of-the-box typography styling that can be easily customized.

#### Additional Information:

I've had a positive experience using this plugin for similar functionality.

![Current Problem](https://github.com/ollama-webui/ollama-webui/assets/108050083/fb8fe504-6865-4da0-89f7-867af8e90509)

**Comment by tjbck** [comment]
Amazing! I'll take a look in a bit to incorporate it into the Web UI. If you manage to get it working in the meantime, PR is welcome 🙏

**Comment by tjbck** [comment]
Just merged the dev branch to main, which enables the markdown styling feature. Thanks for the suggestion!
