### ISSUE TITLE
Is ollama supposed to load automatically in GUI when running through docker

### ISSUE THREAD

**Issue by matsuobasho** [ollama-webui/ollama-webui#272]
# Bug Report

## Description

**Bug Summary:**
I run `docker compose up -d --build` and am able to view the gui at `http://localhost:3000/`.  However, no model shows up in the dropdown.  

**Steps to Reproduce:**
1. On Windows, start Docker desktop
2. After cloning repo, run `docker compose up -d --build` after navigating to it
3. Open up `http://localhost:3000/`

**Expected Behavior:**
Attempt to select model from the drop-down.

**Actual Behavior:**
No model appears.

## Environment

- **Operating System:** Windows 10
- **Browser (if applicable):** Firefox 121.0

## Reproduction Details

**Confirmation:**
- [X] I have read and followed all the instructions provided in the README.md.
- [X] I have reviewed the troubleshooting.md document.   <<-- I'm not running webui and ollama separately AFAIK so should just work?
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

**Comment by tjbck** [comment]
Hi! If you haven't downloaded the models, you'll have to pull the models first! Is it still not showing after you downloaded the models?

**Comment by matsuobasho** [comment]
I'm probably missing something (or maybe the instruction is unclear), but doesn't this say that running `docker compose up -d --build` installs the model as well?

![image](https://github.com/ollama-webui/ollama-webui/assets/13874772/f9aa2cd5-c877-4206-87f9-e71eef60e38e)

Anyways, that's probably a separate issue, but if I download the model, where do I install the model to when I run the docker container?

Thanks

**Comment by tjbck** [comment]
Hi! Ollama does not include models when you first install them, you can download the model by going to the settings > models in the webui. There's also a demo gif demonstrating how you can pull a model in the readme.md. Thanks!
