### ISSUE TITLE
feat: add keyboard shortcuts for keyboard-only users

### ISSUE THREAD

**Issue by jooyoungseo** [ollama-webui/ollama-webui#276]
OpenAI ChatGPT provides some useful keyboard shortcuts. It would be even nicer if this web ui could provide some default keybindings.

![ChatGPT keyboard shortcuts](https://github.com/ollama-webui/ollama-webui/assets/19754711/53ba9c06-c829-4c86-b7cd-2e382352c15e)

**Comment by tjbck** [comment]
Hi, Thanks for the feature request! I'll think of a way to add this feature in the near future, stay tuned!
