### ISSUE TITLE
feat: copy code

### ISSUE THREAD

**Issue by superversivesf** [ollama-webui/ollama-webui#281]
This is a minor feature request but it is a feature the Refact.ai guys put in their Jetbrains client that I found extremely useful. 

All of the code segment boxes have a small copy to clipboard button in the top right had corner of the code window and it copies the contents to the clipboard. 

I've seen the feature on a lot of websites so i'm guessing the behaviour is well supported by web browsers or at least easy to implement. It makes using any generated code segements and getting them into an editor very straight forward, and those are the sort of segments you want to cut and paste typically. 

This seems like a straight forward feature, and it would greatly enhance the utility of the web-ui when asking it coding style questions.

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! You should already have the copy code feature when served over either localhost or https!  With #216, Just added a fix to include the copy code button over http as well, so stay tuned!
