### ISSUE TITLE
Bug in code view? - dev branch

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#285]
![Screenshot from 2023-12-27 20-46-23](https://github.com/ollama-webui/ollama-webui/assets/23272429/9ced370b-5609-48d0-b53c-95d7ef9d213f)

I hope this is just on dev branch. Was trying the RBAC feature and have some models write code, but all responses show no indent code view.

**Comment by tjbck** [comment]
Hi, I cannot seem to reproduce the issue, Here's what the output looks from mine.

<img width="771" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/8d938de6-c7de-4727-8f1b-e5dd903e82ce">

**Comment by tjbck** [comment]
dev branch has been merged to main, let me know if the issue still persists, Thanks!

**Comment by oliverbob** [comment]
May be it has something to do with my version of node/npm. What version of node is compatible with this build?

Coz when I tried to build I saw plenty of warnings related to vite.

**Comment by tjbck** [comment]
Using node v20.10.0, I'll close this issue for now.
