### ISSUE TITLE
Request for Mute or Sound Control Feature in WebUI

### ISSUE THREAD

**Issue by zht1130** [ollama-webui/ollama-webui#288]
**Is your feature request related to a problem? Please describe.**
Yes, the issue relates to the user interface of a web application. I'm always frustrated when I click the 'Play Sound' button in the web UI, but then cannot find an option to turn off the sound. The only workaround seems to be closing the webpage entirely.

**Describe the solution you'd like**
I would like a feature where there is a clear and easily accessible option to mute or stop the sound that starts playing after clicking the 'Play Sound' button. This could be in the form of a 'Mute' button or a toggle to turn the sound off

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. This feature will be added soon after the #216 merge, stay tuned! Duplicate of #269
