### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Ranko-Saotome** [ollama-webui/ollama-webui#294]
I recently updated, and now the application is prompting for an email and password. I'm new to Docker, AI, and related technologies. How can I restore the web UI without being required to enter an email and password?

**Comment by tjbck** [comment]
Hi, Thanks for creating issue! Due to recent reports on losing chat logs and security concerns from some users, we decided to introduce authentication feature with #216. You should have the option to import all your chat logs when you sign up (all your information is saved locally). More detailed instructions here: https://github.com/ollama-webui/ollama-webui#how-to-install-

If you have any other questions or having an issue migrating to a more secure recent version, feel free to reach out anytime, Thanks!

**Comment by Ranko-Saotome** [comment]
I've successfully installed it, created my admin user, but it cannot connect to my local instance of Ollama, which I know is running because I checked. I'm unable to open the settings or anything. I'm using the Brave browser.

**Comment by tjbck** [comment]
Could you share the screenshot of the webui and the commands you used to deploy the webui with us? Thanks!

**Comment by Ranko-Saotome** [comment]
```zsh
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v ollama-webui:/app/backend/data --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main 
```
![Screenshot from 2023-12-27 18-09-09](https://github.com/ollama-webui/ollama-webui/assets/76974974/3a23d82b-765d-4004-9d27-0bea76f54ffa)

![Screenshot from 2023-12-27 18-23-58](https://github.com/ollama-webui/ollama-webui/assets/76974974/eb13b28d-6af5-45fd-ab48-879e0cbf550e)

**Comment by tjbck** [comment]
Hmm, if both ollama and ollama-webui is running on the same machine, here's an alternative method: https://github.com/ollama-webui/ollama-webui/blob/main/TROUBLESHOOTING.md#ollama-webui-server-connection-error

**Comment by Ranko-Saotome** [comment]
That Worked! Thanks.

**Comment by Ranko-Saotome** [comment]
That  got it to connect properly, but I still can't open the settings or the admin panel.

**Comment by tjbck** [comment]
Hmm, the account you logged in with has the admin privilege right? Could you share your browser console logs with us?

**Comment by Ranko-Saotome** [comment]
Also, how would I produce the log files you need? I'm not a developer, but I know my way around if I have some instructions.

**Comment by tjbck** [comment]
Just tried with brave browser on m1, cannot seem to reproduce the issue :/ If possible, could you try accessing the webui from other browser and see if the issue still persists? Also, checking the logs all depends on the system/browser you have, so you'd be better off googling "how to open dev tool". Thanks!

**Comment by Ranko-Saotome** [comment]
Okay, I'm having so many problems. Can you walk me through the steps to revert to the last version before the backend was changed? It was literally so simple to install, but now it's just complicated and buggy.

Also, when I try to log in with my existing username for the account I just created, I keep getting the wrong password or mistyped password, even though I'm directly copying and pasting my password from my password manager.

```

not available
﻿
0.4f11b3d4.js:1 
Object
auth
: 
true
status
: 
true
version
: 
"v1.0.0-alpha.42"
[[Prototype]]
: 
Object
2.fc2f1f5a.js:47 IDB Not Found
2.fc2f1f5a.js:47 
Array(0)
length
: 
0
[[Prototype]]
: 
Array(0)
2.fc2f1f5a.js:47 0.1.17
2.fc2f1f5a.js:36 
Object
API_BASE_URL
: 
"/ollama/api"
models
: 
['mistral-2cores:latest']
notificationEnabled
: 
true
[[Prototype]]
: 
Object
3.54cff0a9.js:1 initNewChat
3.54cff0a9.js:1 
3.54cff0a9.js:1 initNewChat
```

**Comment by tjbck** [comment]
You should be able to revert by pulling the old container image with this command: `docker pull ghcr.io/ollama-webui/ollama-webui@sha256:38a4629859bb94b7aa7206240ccc426b46e8384d580d1b67dd9e214ae38cd2f5`

But I strongly suggest you stay up-to-date with the latest version, I'll try to help you out to the best of my ability so, please bear with me! [Join our discord for faster help](https://discord.gg/5rJgQTnV4s), if you haven't already. Thanks!
