### ISSUE TITLE
feat: convo mode (automatically read out responses, then go back to listening)

### ISSUE THREAD

**Issue by tarbard** [ollama-webui/ollama-webui#295]
**Is your feature request related to a problem? Please describe.**
I have activated the "voice input auto send" option which works nicely but I would like the option to have the response automatically read using TTS without needing to click the speaker icon. Ideally it would also go back into listening mode after reading out the response. This would make it totally interactive without needing user input via keyboard or mouse.

**Describe the solution you'd like**
An additional "enter interactive mode after voice input" option:  When this option is active and the user has sent a message using voice input then the response will be automatically read out using TTS. When it has finished reading out the response it will then go back into "Listening...." mode for the next voice input.  If there is no voice input within the timeout period it can go back to non-interactive mode. 

**Describe alternatives you've considered**
Apologies if this is already a feature - I couldn't find it anywhere.

Thanks for your work on this project, it's really good.

**Comment by tjbck** [comment]
Hi, Thanks for creating this feature request! Sound like a cool feature to have. I will take a look in the near future, stay tuned!

**Comment by tjbck** [comment]
You can now toggle conversation mode from Settings > Voice. Let me know if you encounter any issues!

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/c070ccf2-be47-4241-94b4-174dcbecf7e0)

**Comment by Mikec78660** [comment]
Was this feature taken out again? I don't have voice anymore I have audio and no way to toggle conversation or any way to turn on auto play.
