### ISSUE TITLE
feat: clear all chats from sqlite ollama.db

### ISSUE THREAD

**Issue by qrkourier** [ollama-webui/ollama-webui#296]
**Is your feature request related to a problem? Please describe.**
Chats are now stored in an sqlite3 ollama.db, and there's no way to clear chats.

**Describe the solution you'd like**
A "Clear Chats" button in the left sidebar or settings applet or both removes all chats from the database for the current user.

**Describe alternatives you've considered**
Manually deleting the database or records is a workaround.

**Additional context**
I'm running the ollama-webui built with provided docker-compose.yml from rev e0cbb00899f055ec5496c2c0b119b31f71ec5fa5 on the main branch.

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue. Actively working on this at the moment, stay tuned!

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/f4fd8f0b-4891-486d-94f5-6dc420ecf220)

Feature added with the latest release! Let me know if you encounter any issues, Thanks!
