### ISSUE TITLE
Adminpanel userlist is empty

### ISSUE THREAD

**Issue by Morethanevil** [ollama-webui/ollama-webui#303]
# Bug Report
After the newest version, I created the first user. I tried to view the admin panel and the userlist was empty. I was looking in the docker volumes a databasefile is created and more than 0 bytes. I shutdown the stack and deleted the file, cleared the cache from the browser and wanted to start over. I created a user again, but same result. 

If I want to view the user list it is empty. When I want to go back I am logged out. It does not matter if I use lowercases or uppercases.

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]

Ubuntu server 22.04 latest docker via ofgicial ppa
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

Latest Firefox and brave
## Reproduction Details

**Confirmation:**
- [ x] I have read and followed all the instructions provided in the README.md.
- [x ] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]
Docker container, volume for ollama web-ui is added

Docker-compose.yml appended
[dockercompose.txt](https://github.com/ollama-webui/ollama-webui/files/13785504/dockercompose.txt)

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! That seems very strange, could you verify that you're on the latest version by pulling the latest container? Keep us updated!

**Comment by tjbck** [comment]
<img width="1505" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/fd9bcb89-5519-49f8-8a90-5cf9a82596a0">

Here's what it should look like

**Comment by Morethanevil** [comment]
I tried again, the docker volume `/docker/ollama/ollama-webui:/app/backend/data` is for the web ui, the other one is for ollama itself, storing the modelfiles.

After retrying the problem remains. I append the output of dockerlogs. I am using the web ui behind a reverse proxy, if this helps.

[logs.txt](https://github.com/ollama-webui/ollama-webui/files/13785906/logs.txt)


It looks like this for me

![Screenshot_20231228_120143](https://github.com/ollama-webui/ollama-webui/assets/110860055/e77eb98e-6a18-4e80-a51c-6030022dfd3b)


The db file is created


![Screenshot_20231228_120729](https://github.com/ollama-webui/ollama-webui/assets/110860055/b5408a1e-1ad2-4f5e-b878-f93bc45fda5a)

**Comment by tjbck** [comment]
Oh, I meant I think you might have to replace `/docker/ollama/ollama-webui:/app/backend/data` with `ollama-webui:/app/backend/data`. Are there any reasons for why you're using `/docker/ollama/ollama-webui:/app/backend/data` for the volume mount?

**Comment by Morethanevil** [comment]
Yes I always use bind mounts in every docker project for easier backup, instead of docker volumes. `/docker` is easier to backup instead of `/var/lib/docker/overlay2/64c9c0cf8c9cfb0e2168071df0652a317d49f58a68fe86e4a9a9a525ab9e365e/webui`

And I always need my network settings, because the reverse proxy is not running in docker. I shorted the path to `/docker/ollama/webui` now, but no change

Are there any special permissions for the db file? It is created and owned by root, which is normal and it seems to store data

**Comment by Morethanevil** [comment]
Tried to use the docker volume 

![Screenshot_20231228_123059](https://github.com/ollama-webui/ollama-webui/assets/110860055/cbda2125-3753-4510-8894-ddf73a63314f)


Getting the same error in the logs

![Screenshot_20231228_123031](https://github.com/ollama-webui/ollama-webui/assets/110860055/119d2aa5-17dd-499a-8403-9f1a7ec97427)

**Comment by tjbck** [comment]
The log you see is just a warning log 😅 it shouldn't have any effect on the backend!

**Comment by tjbck** [comment]
<img width="772" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/5e352947-6169-412a-ad2b-a3260c286ad5">

Could you verify that `/users` route is being redirected to`/users/` like above? Thanks.

**Comment by tjbck** [comment]
Also, if you could share the browser console logs or request logs from the network tab in the browser dev tool, that would help us a lot with narrowing down the problem!

**Comment by Morethanevil** [comment]
When I append `/user` to the URL, I am redirected to `/auth`

Mixed Content warning for `/admin`
From Brave:

![1](https://github.com/ollama-webui/ollama-webui/assets/110860055/998fd8c4-990b-4aa8-b5c3-d718f58f1c51)

`/user` is throwing this:

![2](https://github.com/ollama-webui/ollama-webui/assets/110860055/1cbacd86-147b-4517-947e-5290b21a7f8b)

**Comment by tjbck** [comment]
I should've clarified myself, you wouldn't be able to access the users route directly! 

If you could share the logs you get in the dev tool when you visit the admin page, that would be helpful.

Super late where I am currently, will take a look soon as I wake up, Thanks!

**Comment by Morethanevil** [comment]
The first picture was from the adminpanel. Tried again, login and click on my username and then adminpanel
Log from Brave:

[bravelog.log](https://github.com/ollama-webui/ollama-webui/files/13786196/bravelog.log)


There is no more information in the brave dev console and maximum verbose logging :(

![Screenshot_20231228_130210](https://github.com/ollama-webui/ollama-webui/assets/110860055/1102aa32-fd00-4e63-863d-5ede619e3c91)

**Comment by mtompkins** [comment]
Can confirm this user add issue. Posting only to share that it is reproducible.

**Comment by tjbck** [comment]
I'm back, @mtompkins are you also serving the webui over https?

**Comment by tjbck** [comment]
Just identified what's causing the issue, working on a fix! Thank you all for your patience!

**Comment by tjbck** [comment]
Tested the fix over https with cloudflare tunnel, seem to have fixed the issue. Let me know if the issue persists, Thanks a lot!

**Comment by Morethanevil** [comment]
Yes it works now for me, thank you ☺️

**Comment by mtompkins** [comment]
> I'm back, @mtompkins are you also serving the webui over https?

Yes, I use traefik as a proxy. WIll confirm the current change.

**Comment by mtompkins** [comment]
Can confirm this resolves.
Would love a delete user choice :)

**Comment by Morethanevil** [comment]
And disabling registration completly via ENV 🤔

**Comment by tjbck** [comment]
They're all on the roadmap! This is just the beginning, stay tuned for regular updates!
