### ISSUE TITLE
feat: allow admins to enable/disable signup

### ISSUE THREAD

**Issue by ThatOneCalculator** [ollama-webui/ollama-webui#313]
**Is your feature request related to a problem? Please describe.**

I'd like to have a couple friends and family members be able to have their own account, but I don't want anyone on the internet to be able to make one.

**Describe the solution you'd like**

A part of the admin panel that allows signups to be turned on/off

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/70e7a73c-c9fa-476e-8bfb-6e258858b284)

Enable signup toggle button added to the admin panel page with the latest release! Let me know if you encounter any issues, Thanks!

**Comment by ThatOneCalculator** [comment]
Awesome, thank you!

**Comment by ThatOneCalculator** [comment]
[Updated the Rose Pine theme](https://github.com/rose-pine/ollama-webui/commit/2ef82c31966336ac2128eab2e03bcbf75a576a65) to support the new table! 

![image](https://github.com/ollama-webui/ollama-webui/assets/44733677/9194d0ad-e62d-4fd1-b09b-81432a0e20ac)

**Comment by astevensdigi** [comment]
i installed locally and cant get in back to my admin user which was the oly user. uninstalling open-webui and reinstalling doesnt help. i cannot reach the initial signup page. help?
