### ISSUE TITLE
Cannot create admin account

### ISSUE THREAD

**Issue by willjones1977** [ollama-webui/ollama-webui#331]
# Bug Report
Unable to create first account
## Description

**Bug Summary:**
Cannot create admin account

**Steps to Reproduce:**
Serve the web ui from the backend

**Expected Behavior:**
First account gets created

**Actual Behavior:**
No account is created. I queried the ollama.db file and there are no records

In the web interface:
I get the error:
Something went wrong :/
'AuthModel' object has no attribute 'model_dump'

In the terminal, I get:
INFO:     127.0.0.1:51664 - "POST /auths/signup HTTP/1.1" 500 Internal Server Error

## Environment

- Ubuntu 22.04
- Firefox

## Installation Method
Manual install

**Comment by valerybugakov** [comment]
@willjones1977, how did you solve the issue?

**Comment by tjbck** [comment]
@valerybugakov, You might want to reinstall all the python dependencies!

**Comment by valerybugakov** [comment]
Huh, it worked! TY
Curious, why did it fail on the first try? Running these two fixed it for me:

```sh
pip uninstall -y -r requirements.txt
pip install -r requirements.txt
```

**Comment by tjbck** [comment]
@valerybugakov, not entirely sure 😅 Glad it's working for you now!

**Comment by wanakule** [comment]
I lost my admin password and now I can't login. I tried to delete the directory and reinstall all over again but it still remember the old admin account. This is on MacBook Pro M3.
Anything suggestion?
