### ISSUE TITLE
feat: import chats from chatgpt

### ISSUE THREAD

**Issue by MaKraMc** [ollama-webui/ollama-webui#337]
# Bug Report

## Description

**Bug Summary:**
When importing an export from OpenAI ChatGPT, only the chat titles are imported.

**Steps to Reproduce:**
1. Request a data export on chat.openai.com
2. Download the JSON file to your computer
3. Use the import button in the webui under `Settings` > `Chats` > `Import Chats` to upload the json file.

**Expected Behavior:**
All chats and the messages inside these chats are imported.

**Actual Behavior:**
Only chat titles are imported, clicking on them just loads the first message of the currently selected chat (generated inside ollama). It seems that the content of the desired chat can not be loaded correctly.

## Environment

- **Operating System:** Docker (Arch Linux)
- **Browser (if applicable):** Firefox 121.0

## Reproduction Details

**Confirmation:**
- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
```
Object { status: true, version: "v1.0.0-alpha.42", auth: true }
0.0ab3e75d.js:1:17895
IDB Not Found 2.769c9119.js:53:3042
2.769c9119.js:53:3071
Array []
2.769c9119.js:53:3193
0.1.17 2.769c9119.js:53:2668
Object { theme: "dark" }
2.769c9119.js:37:1800
Object { title: "Docker", create_time: 1692297894.074992, update_time: 1699966252.486769, mapping: {…}, moderation_results: [], current_node: "5b6548f0-e767-44bc-84dc-f42e2997a38e", plugin_ids: null, conversation_id: "888446df-9fe0-4a46-8466-1d118c56f94f", conversation_template_id: null, gizmo_id: null, … }
5.35b8f20a.js:1:5817
Uncaught (in promise) ReferenceError: convertMessagesToHistory is not defined
    Immutable 33
    <anonymous> http://localhost:3000/c/7da6fc15-a2fc-4ae5-b580-b35fa847f6ea:43
    promise callback* http://localhost:3000/c/7da6fc15-a2fc-4ae5-b580-b35fa847f6ea:42
5.35b8f20a.js:1:5944
Object { title: "Powershell", create_time: 1690188844.076927, update_time: 1698762971.854363, mapping: {…}, moderation_results: [], current_node: "4b7cd78d-af00-4221-adb6-29c050c31c27", plugin_ids: null, conversation_id: "4264f381-de03-4c88-a174-c979236c4237", conversation_template_id: null, gizmo_id: null, … }
5.35b8f20a.js:1:5817
Uncaught (in promise) ReferenceError: convertMessagesToHistory is not defined
    Immutable 30
5.35b8f20a.js:1:5944
Object { title: "Kubernetes DE", create_time: 1678095017.793144, update_time: 1697093919.223057, mapping: {…}, moderation_results: [], current_node: "8ca3e205-f254-4746-b1e9-c56d72a889dd", plugin_ids: null, conversation_id: "5694c673-cf4a-4e36-8260-58f815da50c9", conversation_template_id: null, gizmo_id: null, … }
5.35b8f20a.js:1:5817
Uncaught (in promise) ReferenceError: convertMessagesToHistory is not defined
    Immutable 30
5.35b8f20a.js:1:5944
```

**Docker Container Logs:**
```
http://ollama:11434/api/version

INFO:     172.18.0.1:38260 - "GET /version HTTP/1.1" 200 OK

INFO:     172.18.0.1:38248 - "GET /chats/2b3042f7-67c1-4e00-afdb-d38eda020ced HTTP/1.1" 200 OK

INFO:     172.18.0.1:45464 - "GET /chats/086c0bac-7d11-45fa-a6b7-32ea7265168f HTTP/1.1" 200 OK
```

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

Docker (compose)

## Additional Information

My export from openAI is about 2.7 MB in size.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Hi @MaKraMc, Thanks for creating this issue! FYI, Import/Export Chat logs feature is for Ollama WebUI Only, and is not compatible with ChatGPT at the moment. However, that seems like a great feature to have, so If you manage to implement the feature, Feel free to create a PR, Thanks!

**Comment by anuraagdjain** [comment]
Are we looking to import `conversations.json` from OpenAI's data export?

**Comment by MaKraMc** [comment]
Yes, that was what I was referring to. I actually did a comparison between both conversations.json from OpenAI and an export from Ollama Webui and they look quite similar. I think a few JSON mappings could do the trick but I'm no expert on that topic.

**Comment by bhulston** [comment]
@anuraagdjain Are you already working on this? If not I'm happy to tackle this one

**Comment by anuraagdjain** [comment]
> @anuraagdjain Are you already working on this? If not I'm happy to tackle this one

I planned to, but you can take this. Could you please tag me in your PR? I'd like to just view it 🙏

**Comment by bhulston** [comment]
> Yes, that was what I was referring to. I actually did a comparison between both conversations.json from OpenAI and an export from Ollama Webui and they look quite similar. I think a few JSON mappings could do the trick but I'm no expert on that topic.

@MaKraMc Did you try importing the ollama-web-ui export as well? Just checking if that worked okay for you (on my end it didn't so I'm gna double check that code as well)

**Comment by MaKraMc** [comment]
You are right. After importing the history from ollama webui itself, the titles are there but the chats can not be loaded. When clicking on an imported chat, I see the JSON object of the chat followed by an error message:

```
Uncaught (in promise) ReferenceError: convertMessagesToHistory is not defined
    Immutable 37
5.db3313fe.js:1:5965
```

**Comment by bhulston** [comment]
> You are right. After importing the history from ollama webui itself, the titles are there but the chats can not be loaded. When clicking on an imported chat, I see the JSON object of the chat followed by an error message:
> 
> 
> 
> ```
> 
> Uncaught (in promise) ReferenceError: convertMessagesToHistory is not defined
> 
>     Immutable 37
> 
> 5.db3313fe.js:1:5965
> 
> ```

Yah I got the same issue, just wanted to make sure it wasn't just me. Thanks for checking. 🤟

Looks like a simple import issue?, but probably gta run some tests. I've also started on parsing GPT responses so I'll keep you updated!

**Comment by justinh-rahb** [comment]
Exports generated by the migration to user authentication imported fine, but exports generated since then have been unimportable, I've experienced the same as the rest of you. Titles show, but no content in chats is visible.

**Comment by bhulston** [comment]
https://github.com/ollama-webui/ollama-webui/pull/486

Added a PR to fix chat imports for ollama-webui exports. Once this goes through, will add changes to correctly format OpenAI export to match ollama-webui one and it should be good 👍

**Comment by madman2012** [comment]
I cannot get the import of chats to work from either openai json or ollama's. Hopefully it gets fixed soon!

**Comment by bhulston** [comment]
@madman2012 
You would likely have to pull the GitHub updates into your docket from the new merge for ollama ones to work

Working on the OpenAI one and hoping to be done tonight

**Comment by bhulston** [comment]
Added a PR for this issue! Once it goes through, importing chat histories should work well!
https://github.com/ollama-webui/ollama-webui/pull/496
