### ISSUE TITLE
A blank page

### ISSUE THREAD

**Issue by heweapon** [ollama-webui/ollama-webui#362]
# Bug Report

## Description

**Bug Summary:**
I can get page of register when I access 172.16.120.14:3000.But when I signed in, there was just a blank page
I used this command to install: docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v ollama-webui:/app/backend/data --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main

I deployed Ollama and Ollama-webui on docker on the LAN
![error13](https://github.com/ollama-webui/ollama-webui/assets/49176896/166bd9d5-3842-407d-9728-6a04663a0b4e)

![error0](https://github.com/ollama-webui/ollama-webui/assets/49176896/2ac15f00-98fe-484b-9022-9dbc71726e35)

Here's what I tested after using VScode to connect to the server over SSH

![dockercontainer](https://github.com/ollama-webui/ollama-webui/assets/49176896/a377cee4-3232-47f9-b4f0-98e6c40f552d)

![dockerrun](https://github.com/ollama-webui/ollama-webui/assets/49176896/eab15d5e-4b10-497a-bc7a-ee86742a7d14)

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! Could you try deleting your browser cache and see if that does anything for you? Keep us updated!

**Comment by heweapon** [comment]
> Hi, Thanks for creating this issue! Could you try deleting your browser cache and see if that does anything for you? Keep us updated!

Yes, I tried it. Neither deleting the browser cache nor changing the browser solved the problem.(I use Chrome and Edge)

**Comment by tjbck** [comment]
Hmm, could you try setting a different port? Keep us updated!

**Comment by heweapon** [comment]
> Hmm, could you try setting a different port for the webui and see if that does anything? Keep us updated!

Ok, I'll try

**Comment by heweapon** [comment]
> Hmm, could you try setting a different port for the webui and see if that does anything? Keep us updated!

I modified the port according to what you said and changed it to 3001:
![010403](https://github.com/ollama-webui/ollama-webui/assets/49176896/a599ece7-b1a9-4af8-a0f3-c399636949c0)
Its running status on Docker on linux server is as follows:
![010404](https://github.com/ollama-webui/ollama-webui/assets/49176896/4eb441f1-2bc6-497e-b44f-39955ca6ac22)
Now the browser can load the Ollama-webui page, but the following problem occurs:
![010402](https://github.com/ollama-webui/ollama-webui/assets/49176896/7ddd1095-7b0b-405b-bbe9-c4730813ab6a)
![010401](https://github.com/ollama-webui/ollama-webui/assets/49176896/e4abf3c0-2a47-4d42-85b5-30dd0fff652d)
Thank you very much for your patience!

**Comment by tjbck** [comment]
You might want to try the alternative command in our troubleshooting.md! https://github.com/ollama-webui/ollama-webui/blob/main/TROUBLESHOOTING.md

**Comment by heweapon** [comment]
OK. I'll try

**Comment by heweapon** [comment]
> You might want to try the alternative command in our troubleshooting.md! https://github.com/ollama-webui/ollama-webui/blob/main/TROUBLESHOOTING.md

OK. I'll try
