### ISSUE TITLE
Downloading model keeps spamming "pulling xyz"

### ISSUE THREAD

**Issue by Joly0** [ollama-webui/ollama-webui#367]
# Bug Report

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]
I tried to download falcon model and just saw this:
![grafik](https://github.com/ollama-webui/ollama-webui/assets/13993216/5787c95a-aac9-4624-8e40-b34c06b987c0)
spammed over and over again until the model was finished downloading. Would be great to see a progress instead of this

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]
Download falcon model

**Expected Behavior:**
[Describe what you expected to happen.]
No spam

**Actual Behavior:**
[Describe what actually happened.]
Spam

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**
- [X] I have read and followed all the instructions provided in the README.md.
- [X] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! It seems like you're using an outdated version of ollama-webui, please update to the latest version by following the commands here: https://github.com/ollama-webui/ollama-webui#installing-ollama-web-ui-only, Thanks!

**Comment by Joly0** [comment]
Ah, i see i was still using the dockerhub image, which was replaced by the ghcr image
