### ISSUE TITLE
Option to disable individual login

### ISSUE THREAD

**Issue by canytam-krystal** [ollama-webui/ollama-webui#376]
**Is your feature request related to a problem? Please describe.**
The new login feature is not necessary in some situation.

**Describe the solution you'd like**
I want an option to disable the login. 

**Describe alternatives you've considered**
A guest login that don't need any registration is also OK.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! For security reasons, we do not plan on adding an option to remove the login feature in the near future, so I'll close this issue as not planned for now. However, https://github.com/ollama-webui/ollama-webui-lite will provide with the option to use the webui without any of the additional backend functionalities (including auth), so stay tuned for that!

**Comment by vhscom** [comment]
I saw a connection failure locally, rebuilt containers and then saw the login screen. Was a bit shocked. But found my clarity here. Happy to see there's a light version and hope the local-first crowd will benefit regularly from upstream. 🙏
