### ISSUE TITLE
feat: incognito mode for chat

### ISSUE THREAD

**Issue by jeremiahsb** [ollama-webui/ollama-webui#382]
**Describe the solution you'd like**
Chat history is great, though there are some instances where it would be nice to be able to temporarily disable the chats going into the history, for example if one is playing around with different, repeated prompts. It would be great to have a toggle that could put the UI into "incognito" or "off the record" mode where the chats wouldn't go to the history.

**Describe alternatives you've considered**
There are a couple of ways of handling this now. It's possible to delete the chat history one by one, or create a second user profile (and delete it when done) but the toggle would be easier.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! I'll try to implement this feature in the near future, stay tuned!

**Comment by tjbck** [comment]
Just added this feature with the latest release! You can toggle incognito mode from the settings, Let me know if you encounter any issues, Thanks!

<img width="629" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/b6cfd8a7-14b9-46cf-9bf6-0e6061217700">
