### ISSUE TITLE
External Ollama and interfacing UI

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#392]
**Is your feature request related to a problem? Please describe.**
Since there hasn't been a good doc to support various servers (apache, ngingx, caddy, flask) coz I know you're extremely busy for more and more features, can I in stead request for an integration of an option to select server connection:
when [...]

**Describe the solution you'd like**
Since we now have the ability to interface with any external host (I'm glad there's no more problem about the http/https in the Ollama API URL, see screenshot and thanks), it should be very nice to be able to shift to the `--add-host=host.docker.internal:host-gateway` or the external `Ollama hosted on the cloud`. 

**Additional context**
![models](https://github.com/ollama-webui/ollama-webui/assets/23272429/1b1dd233-e248-4247-bc8b-37f0e6bfd3ff)

**Comment by tjbck** [comment]
I'll merge this issue with #278! Let's continue our discussion there!
