### ISSUE TITLE
Can't see pull progresse when using Docker image version and simple local isntallation option

### ISSUE THREAD

**Issue by Abdoulaye-Sayouti** [ollama-webui/ollama-webui#394]
![Screenshot from 2024-01-05 10-58-57](https://github.com/ollama-webui/ollama-webui/assets/76700746/669550b8-450a-4831-97d6-39a10f9ec398)
# Bug Report

## Description

**Bug Summary:**
Can't see pull progresse when using Docker image version and simple local isntallation option. . And the chat doesn't work  after the pull.

**Steps to Reproduce:**
1-) Install Ollama web ui with : 
docker compose -f docker-compose.yaml -f docker-compose.gpu.yaml -f docker-compose.api.yaml up -d --build
or
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v ollama-webui:/app/backend/data --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main

2-) Try to pull a model

**Expected Behavior:**
When start downloading a model, the progress bar should show the pull progress. And the chat should work too after the pull.

**Actual Behavior:**
When start downloading a model, the progress bar don't show up. And the chat doesn't work  after the pull.

## Environment

- **Operating System:** On Ubuntu 22.04 with NVIDIA RTX 3070 Laptop
- **Browser (if applicable):** Firefox 103.0.1

**Comment by tjbck** [comment]
Hi, Thanks for reporting this issue! I can't seem to reproduce the issue on all three of my machines (ubuntu, macos, windows). Could you try pulling the latest release and reinstalling everything? Keep us updated, Thanks!

**Comment by Abdoulaye-Sayouti** [comment]
Thanks for your response.

It's working now. Apparently the issue was with the browser. I tried Brave and it worked, then updated Firefox and it worked perfectly.

Thanks again.

**Comment by tjbck** [comment]
Glad its working for you!
