### ISSUE TITLE
Unable to create a new chat

### ISSUE THREAD

**Issue by KshitizSharmaV** [ollama-webui/ollama-webui#412]
Description

## Bug Summary:
When trying to create a new chat, an internal server error (500) occurs, accompanied by Unhandled Promise Rejections due to SyntaxError in specific scripts. This issue seems to have appeared in the latest two updates.

### Steps to Reproduce:
Open the application.
Attempt to create a new chat.
Observe the errors.

### Expected Behavior:
The application should allow the creation of a new chat without encountering server errors or script issues.

### Actual Behavior:
The server responds with a status of 500 (Internal Server Error) when attempting to create a new chat. Additionally, there are Unhandled Promise Rejections due to SyntaxError in certain JavaScript files.

### Environment
Operating System: [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
Browser (if applicable): [e.g., Chrome 100.0, Firefox 98.0]
Reproduction Details

### Confirmation:
 I have read and followed all the instructions provided in the README.md.
 I have reviewed the troubleshooting.md document.
 I have included the browser console logs.
 I have included the Docker container logs. - I'm running the app with 'sh start.sh'

###  Logs and Screenshots
<img width="1792" alt="Screen Shot 2024-01-07 at 3 13 50 PM" src="https://github.com/ollama-webui/ollama-webui/assets/12647113/64130a74-c614-4bcd-a27a-abf7e965f33d">

### Browser Console Logs:
```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (c567652a-7835-4373-b7c6-b146a215aabc, line 0)

[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
    (anonymous function) (5.d4cc8201.js:7:12240)
    asyncFunctionResume
    (anonymous function)
    promiseReactionJobWithoutPromise
    promiseReactionJob

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (new, line 0)

[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
    (anonymous function) (3.0f2fdfcf.js:7:11687)
    asyncFunctionResume
    (anonymous function)
    promiseReactionJobWithoutPromise
    promiseReactionJob
Docker Container Logs:
[Include relevant Docker container logs, if applicable]
``` 

Additional Information

The issue seems to be related to the latest two pushes. It is critical to investigate the changes made in these updates to identify the root cause of the server errors and syntax issues.

Note

This bug report follows the provided instructions and includes all necessary information for reproduction and addressing of the issue. Further analysis of the recent updates and detailed examination of the logs and scripts mentioned are required for resolution.

**Comment by KshitizSharmaV** [comment]
I'm able to add more prompts to the existing chat, the problem is happening while I'm creating a new chat.

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! I cannot seem to reproduce the issue at all, and I have not modified any of the codes for creating new chats. Could you try clearing browser cache and see if that does anything? Keep us updated, Thanks!

**Comment by KshitizSharmaV** [comment]
Thanks let me try

**Comment by KshitizSharmaV** [comment]
False Alarm, My sincere apologies. Would double check next time.

**Comment by KshitizSharmaV** [comment]
Actual Issue: I was making a manual update to the .db file via SQLite browser and didn't finish saving the change. The Db got locked and the application wasn't able to access it. 

Solution: Try closing the other application accessing the same .db file.
