### ISSUE TITLE
Support for uploading a large Modelfile

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#426]
Example, I have a book or document long Modelfile. Is it possible to have the ability to import it (not just json) and then create prompt suggestions based on that?

Thanks.

**Comment by tjbck** [comment]
Hi, I'll close this issue as not planned, it seems like there's quite a bit of a duplicate content with your new feature request. When you make a new request please try to provide as much information as possible, if not it's quite hard to tell what exactly you're requesting, thanks.
