### ISSUE TITLE
feat: option to disable suggested prompts

### ISSUE THREAD

**Issue by coder543** [ollama-webui/ollama-webui#440]
**Is your feature request related to a problem? Please describe.**
Depending on screen size, there are 2 to 4 suggested prompts shown above the chatbox when starting a new conversation. Because I guess I'm clumsy, I keep accidentally hitting these especially when using the UI from my phone. This is very annoying, and I honestly can't imagine anyone actually using any of these suggested prompts unless it is their first time using an LLM.

**Describe the solution you'd like**
An option in the settings to disable suggested prompts.

**Additional context**
![image](https://github.com/ollama-webui/ollama-webui/assets/726063/5bf201ae-059f-40af-b128-92f19c9b9273)

**Comment by justinh-rahb** [comment]
Option to remove _or_ customize would be my preferred option, personally.

**Comment by jukofyork** [comment]
Yeah, I've clicked these by accident several times using my phone.
