### ISSUE TITLE
Infinite generation hangs the model completely

### ISSUE THREAD

**Issue by vladfaust** [ollama-webui/ollama-webui#444]
# Bug Report

## Description

**Bug Summary:**
Self-hosted LLMs are known to accidentally enter loop mode, repeating the same sequences again and again, forever.
If it happens in Ollama WebUI, then pressing the stop button only stops the generation visually, but no further generation using the same model is possible, neither in this nor in any other chat; the interface hangs similar to this:
![image](https://github.com/ollama-webui/ollama-webui/assets/7955682/883d9e47-3d4b-4f5c-bacd-9b110f50149a)
And the only solution is to reboot the model (the system).

**Steps to Reproduce:**
I'm not sure how to trigger the loop, it just happens.

**Expected Behavior:**
Once I stop a request, or reload the UI, the model shall stop streaming, instead of the HTTP request remaining hung.
At the very least, the "stop" button in the UI should work correctly.

**Actual Behavior:**
It ceases to function correctly.

## Environment

- **Operating System:** Ubuntu
- **Browser (if applicable):** Chrome
## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

I run Ollama Web UI locally, and connect it to an external Ollama API (self-hosted).

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! I'd love to implement that feature, but afaik Ollama does not offer such apis at the moment, so I'll close this issue for now. But feel free to create an issue on Ollama repo and link this issue, Thanks!
