### ISSUE TITLE
Switching between conversations kills response streaming

### ISSUE THREAD

**Issue by robertvazan** [ollama-webui/ollama-webui#452]
# Bug Report

## Description

**Bug Summary:**
Response streaming works only if you stay in one conversation.

**Steps to Reproduce:**
1. Start a new chat. Model starts streaming the response.
2. Switch to an older chat while the model is still responding.
3. Switch back to the new chat.

**Expected Behavior:**
Response streaming should continue in the background. Switching back should show current state of the response.

**Actual Behavior:**
The response is gone along with all controls.

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

I will provide additional information if you cannot reproduce the bug with the information provided so far.

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! Unfortunately, because of the nature of the apis provided by Ollama (LLM providers in general), there isn't a quick fix for this. FYI, ChatGPT also experiences this issue as well. I'll close this issue as not planned for now, but I'll see if what I can do anything to accomodate your use case, thanks!

**Comment by robertvazan** [comment]
ChatGPT is much faster though. It's surprising that it's hard to resume streaming when the backend keeps consuming the stream anyway even after the client disconnects. I guess the best workaround here is to open separate browser tab.

**Comment by robertvazan** [comment]
BTW, ChatGPT does not discard the response but rather cancels it, keeping what was generated so far. It also makes it easier to regenerate the response. Ollama WebUI instead keeps consuming the response in the background with no way to see what's going on and no way to stop the process.

**Comment by justinh-rahb** [comment]
@robertvazan it's important to note that ChatGPT runs on an infrastructure of 10,000+ GPUs, one of which is dedicated to generating your response, even if you think you've canceled the request from your end. In contrast, the Ollama WebUI operates using a single instance of Ollama, and does not support high concurrency or initiating a new generation while another is still being processed.

This limitation arises from the upstream project that provides the API utilized by this webui. As @tjbck suggested, there isn't a quick solution to this issue, as it originates from the core functionality of that project.

**Comment by robertvazan** [comment]
@justinh-rahb Isn't Ollama CLI using the same APIs? If I press Ctrl+C in the CLI, the response is cancelled immediately and CPU load drops to zero in a second or two. Ditto if I invoke the API directly via curl and press Ctrl+C to cause curl to close the connection. So as far as I can tell, closing the connection is an easy way to cancel the whole process on ollama side.

**Comment by tjbck** [comment]
@robertvazan I'll see what can be done, It's just that I'm incredibly busy this week so I don't have the capacity to take a look at the moment. If you manage to find a solution in the meantime, feel free to make a PR!

**Comment by robertvazan** [comment]
@tjbck Just fixing #456 and stopping generation automatically when user switches chats (like ChatGPT does it) would be sufficient as a fix. Keeping streaming in the background and showing an up-to-date response when user navigates back would be a new feature, a convenient and useful one.

**Comment by tjbck** [comment]
@robertvazan If you could test that it works as expected with only using APIs provided by Ollama, instead of comparing it to ollama CLI, that would be tremendously helpful!

**Comment by robertvazan** [comment]
@tjbck I did test it with the API directly. I executed the first curl example from [ollama chat API docs](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion) with "Write a long blog post" prompt and pressed Ctrl+C while it was in the middle of the first paragraph. Curl exited, connection was closed, and ollama CPU usage dropped to zero almost immediately.
