### ISSUE TITLE
Change the default 8080 port or use an environment variable

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [ollama-webui/ollama-webui#453]
When running the webui directly on the host with `--network=host`, the port 8080 is troublesome because it's a very common port, for example phpmyadmin uses it.

It would be nice to change the default port to 11435 or being able to change it with an environment variable.

For now I can't run the webui since the default docker run command doesn't work (Server connection error) and making it run on the host conflicts with phpmyadmin.

**Comment by anuraagdjain** [comment]
I'm assuming you're using docker with `--network=host`. I'm curious, why `-p <new-port>:8080` doesn't work?

**Comment by anuraagdjain** [comment]
I have this PR https://github.com/ollama-webui/ollama-webui/pull/454. Using `SERVER_PORT` you can modify the default port from 8080. Can you test ?

**Comment by anuraagdjain** [comment]
> > I have this PR #454. Using `SERVER_PORT` you can modify the default port from 8080. Can you test ?
> 
> I tried to build the [image](https://github.com/anuraagdjain/ollama-webui/blob/feat/custom-server-port/Dockerfile) but the build fails (Ubuntu 22.04).
> 
> ```
> > [base 11/11] COPY ./backend .:
> ------
> Dockerfile:49
> --------------------
>   47 |     # RUN python -c "from sentence_transformers import SentenceTransformer; model = SentenceTransformer('all-MiniLM-L6-v2')"
>   48 |     
>   49 | >>> COPY ./backend .
>   50 |     
>   51 |     CMD [ "sh", "start.sh"]
> --------------------
> ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref d8277cfd-3c1f-4ebc-9dad-43ef42114884::rz2789ejxt8rbj2osmnolcken: "/backend": not found
> ```

Didn't get any issue here. The build was successful 🤔 . Can you prune older images and retry?

**Comment by Alexandre-Fernandez** [comment]
It's working
