### ISSUE TITLE
Feat: I keep misclicking the text to voice button! Suggestions inside.

### ISSUE THREAD

**Issue by jukofyork** [ollama-webui/ollama-webui#455]
When clicking the info button, I keep clicking the little speaker button and then have to listen to everything get read out!

I think we need:

1. Some way to stop the voice to text.
2. Possibly the option to disable it in the options.
3. Spread the buttons out slightly more or make them a little bit bigger.

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! If you're on the latest version of the webui, you already have the option to stop the TTS by clicking on the same "speech" button again. I'll close this issue for now, but I'll consider implementing an option to customise the buttons in the near future, Thanks!
