### ISSUE TITLE
Close connection to ollama when stop button is pressed

### ISSUE THREAD

**Issue by robertvazan** [ollama-webui/ollama-webui#456]
# Bug Report

## Description

**Bug Summary:**
Stop button (#48) does not really work, because WebUI backend keeps streaming the response from ollama. This also causes #444 and the same problem contributes to poor UX in #452. WebUI backend should close connection to ollama to stop generation.

**Steps to Reproduce:**
1. Ask a slower model to write something longer.
2. Press stop button.

**Expected Behavior:**
CPU usage drops immediately. New question can be asked immediately.

**Actual Behavior:**
While the client indeed stops receiving tokens immediately, ollama apparently continues to generate the whole response in the background, which blocks other chat requests. The only way to stop the generation is to restart ollama process.

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Additional Information

The root cause of the issue is that WebUI backend fails to close connection to ollama. My experiments with ollama API show that closing the connection cancels generation immediately with no further CPU usage. Ollama's built-in CLI client apparently does this when you press Ctrl+C.

As I understand it, there's a connection chain:

WebUI frontend <-> WebUI backend <-> ollama

Frontend-backend connection is closed/cancelled properly, judging by browser console messages. But backend-ollama connection apparently stays open.

**Comment by jukofyork** [comment]
Yeah, this can be very problematic if you are using a model that sometimes goes wrongs and gives out and infinite repeating response. I had to ssh into the host machine and do a kill - 9 on the ollama process to get it working again.

**Comment by tjbck** [comment]
Might be relevant: https://github.com/tiangolo/fastapi/discussions/8805

**Comment by robertvazan** [comment]
@tjbck This mostly works. Thanks! One issue though: Why does it take 15 seconds for ollama to go quiet after cancelling the response in UI? My experiments on API level show that ollama CPU usage should drop in under 3 seconds after connection is closed.

**Comment by robertvazan** [comment]
PS: It takes much longer with larger models. Do you have a buffer somewhere that needs to process a certain number of tokens before it can close the connection?

**Comment by robertvazan** [comment]
This is broken again. Ollama WebUI keeps streaming the rest of the response after I press stop button.

**Comment by tjbck** [comment]
@robertvazan Hmm, AFAIK there hasn't been any changes from the webui side. Could you verify that the issue is from the webui? Thanks!
