### ISSUE TITLE
feat: model name sanitisation

### ISSUE THREAD

**Issue by robertvazan** [ollama-webui/ollama-webui#457]
# Bug Report

## Description

**Bug Summary:**
Model download does not strip whitespace from model name. This results in confusing error messages. Whitespace gets there easily when copy-n-pasting from ollama library.

**Steps to Reproduce:**
Just enter " tinyllama" or "tinyllama " (with the space) in the form and click download.

**Expected Behavior:**
Whitespace is stripped and download starts.

**Actual Behavior:**
Error "pull model manifest: file does not exist"

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Additional Information

It would be great to also accept the full command from ollama library, e.g. "ollama run tinyllama", or an URL, which are both easy to copy-n-paste.

**Comment by anuraagdjain** [comment]
Good catch, missed this case when refactored the logic for multiple downloads ([PR](https://github.com/ollama-webui/ollama-webui/pull/465)).
