### ISSUE TITLE
Need a way to stop ollama generating text - a stop button

### ISSUE THREAD

**Issue by abulka** [ollama-webui/ollama-webui#46]
Please add a stop button which stops ollama generating text

I recently had a answer that just didn't stop. Ollama was spewing out a ranting answer that never stopped. I didn't know how to get out of my situation.

**Comment by tjbck** [comment]
Hi, Sounds good! I'll add the feature soon.

**Comment by tjbck** [comment]
Implemented with #48. Keep us in the loop and let us know if it's working as intended for you. Thanks.
