### ISSUE TITLE
Add configuration to disable or remove Gravatar default avatar.

### ISSUE THREAD

**Issue by puresick** [ollama-webui/ollama-webui#462]
**Is your feature request related to a problem? Please describe.**
There is an external network request being made for the simple account picture placeholder. If you are running ollama and ollama-webui locally, there is a good chance you might not want that to happen.

**Describe the solution you'd like**
Some way of disabling this from happen. Maybe as an environment variable or as a setting in the admin panel UI.

**Describe alternatives you've considered**
Since there is no functionality to update the profile picture using Gravatar maybe remove that request completely and use a local default picture instead.

**Additional context**
![image](https://github.com/ollama-webui/ollama-webui/assets/2714266/d1a980b0-17c3-498e-b7cf-c1e225da6f64)

**Comment by justinh-rahb** [comment]
Before the user authentication feature was merged, the use of Gravatar was optional. I agree that it would be best to keep this option available for users and provide a way to enable or disable it.

That being said, I'm also curious about your thoughts on web applications that use assets from CDNs, as this is a common practice. Where do we draw the line on this? How far should we go in removing external network requests?

**Comment by puresick** [comment]
That would be great! :)

Having a hardline on "no external network requests" would be the optimum, since it would allow for completely private instances hosted on any machine. On the other side can this make some things more difficult.

In general, I would suggest to prevent external requests for simple assets which do not get updated frequently or the update is not necessary, e.g. default user profile picture, some CSS reset file, external JS libraries which are needed during runtime.
Other things like the model files (I know this is managed my ollama itself rather than the webui, but just using it as example scenario here) should be requested over the network by default because you always want to most recent version and the best UX to get things started. In such cases it would be great though to have the configuration option to disable these requests if someone wants to completely lock down their instance.

**Comment by tjbck** [comment]
With #584, webui uses local "user.png" image by default! Users can also edit their profile image in the settings now, let me know if you encounter any issues!

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/ad3e946c-757d-4129-923f-b791684ebe8b)

**Comment by puresick** [comment]
Works like a charm, thank you!
