### ISSUE TITLE
Option to stop auto-scroll

### ISSUE THREAD

**Issue by abulka** [ollama-webui/ollama-webui#47]
**Is your feature request related to a problem? Please describe.**
When I'm waiting for the full answer to appear I often like to scroll backwards and read the start of the answer.  Currently I cannot scroll back because as soon as I do, the UI scrolls me to the bottom again!

**Describe the solution you'd like**
Allow me to scroll backwards. Only engage "auto keep to the bottom" mode if I have actually scrolled to the bottom of the page. Alternatively add an option to turn off auto scroll to the bottom.

See ChatGPT for the behaviour I am describing, which ChatGPT has already implemented.

**Comment by tjbck** [comment]
Hi, I'll think of ways to add that as well, Thanks!

**Comment by tjbck** [comment]
Implemented with #48. Keep us in the loop and let us know if it's working as intended for you. Thanks.
