### ISSUE TITLE
Proxy support for downloading the models

### ISSUE THREAD

**Issue by m-hoseyny** [ollama-webui/ollama-webui#476]
Hello,

In some countries, there are Internet limitations that would not let us download models from the main repo. Is it possible that the proxy setting (socks5 or HTTP) has been set until the downloader uses the proxy to download the model?

Thanks

**Comment by justinh-rahb** [comment]
Ollama WebUI does not have direct control over the model download process as it is handled by the Ollama application itself. Therefore, adding proxy support for model downloads would need to be implemented upstream in the Ollama project.
