### ISSUE TITLE
feat: general TTS improvements

### ISSUE THREAD

**Issue by horiacristescu** [ollama-webui/ollama-webui#478]
**Is your feature request related to a problem? Please describe.**

Allow selecting the voice/speed for TTS and start speech immediately as we have text, not after it stops generating. The default voice is not great on Mac OS.

Alternatively, allow selection of text in order to trigger system TTS. By comparison, OpenAI's chat interface does not hinder text selection and system TTS while appending words to the last paragraph. 

**Describe the solution you'd like**
When you generate a response, it is impossible to select a paragraph because selection moves by itself to include everything.
When using TTS there is no way to set the voice and speed, forcing low quality TTS on the users.

**Describe alternatives you've considered**
Either support better copy & paste while appending words, or improve the TTS config.

**Additional context**
-

**Comment by justinh-rahb** [comment]
Related: #126

**Comment by tjbck** [comment]
I'll merge this issue with #126, let's continue our discussion there!
