### ISSUE TITLE
Add the support for search internet

### ISSUE THREAD

**Issue by ChingWeiChan** [ollama-webui/ollama-webui#487]
**Is your feature request related to a problem? Please describe.**
The information in local LLM is often old.

**Describe the solution you'd like**
I want to use search API to make the local LLM (ollama) can search the internet and use RAG.

**Describe alternatives you've considered**
I found SerpApi is supported by LangChain. 
https://python.langchain.com/docs/integrations/providers/serpapi

**Additional context**
SerpApi is google search api and then can allows you to access Google search results.

**Comment by justinh-rahb** [comment]
Related: #464

**Comment by tjbck** [comment]
Let's continue our discussion here: #464
