### ISSUE TITLE
feat: chat message search support

### ISSUE THREAD

**Issue by hemangjoshi37a** [ollama-webui/ollama-webui#497]
*Search box for all chat like VSCode search box for all files.*

Here the search box in the left panel should not only search the chats with search string but also with all chat history of all the chats. something like vs code file search.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! I'll be closing this as I personally don't see myself implementing this anytime soon, but feel free to make a PR with the feature if you (or anyone) manage to implement it, Thanks!

**Comment by hemangjoshi37a** [comment]
If you can not develop this then at least keep it open if anyone wants to develop. why do you rush so much to close it ?
