### ISSUE TITLE
Dockerfile.dev fails 

### ISSUE THREAD

**Issue by dnck** [ollama-webui/ollama-webui#523]
# Bug Report

## Description

**Bug Summary:**
Building the `Dockerfile.dev` container image fails with the message,
```
...
ERROR: Cannot install -r requirements.txt (line 22) because these package versions have conflicting dependencies.

The conflict is caused by:
    sentence-transformers 2.2.2 depends on torch>=1.6.0
...
```
I assume this is due to a missing dependency in the `backend/requirements.txt` file, but I can't be certain yet.

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]
```
podman build -f ./Dockerfile.dev -t foobar
```
**Expected Behavior:**
[Describe what you expected to happen.]

Build successfully 

**Actual Behavior:**
[Describe what actually happened.]
It did not build.

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]

Ubuntu 22.04 lts

- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

n/a

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [ X I have reviewed the troubleshooting.md document.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue. Could you tell us more about `Dockerfile.dev` file? I'm guessing it might be a podman syntax which I'm not very familiar with. I can confirm that the build using docker works fine in all my macos, windows, ubuntu machines. We only support containerising using docker officially, so you might want to open an issue on their repo if possible!

**Comment by dnck** [comment]
I closed the issue. It turns out that I just needed to install torch inside the container.
