### ISSUE TITLE
Persistent OpenAI Key for Continued Access to ChatGPT Models

### ISSUE THREAD

**Issue by Grepta** [ollama-webui/ollama-webui#546]
**Is your feature request related to a problem? Please describe.**
When restarting Ollama Web UI, any Open AI API key added in settings is cleared. This means each time the an API key needs to be re-added to get access to ChatGPT models.

**Describe the solution you'd like**
The option for persistent storage of the API key.

**Describe alternatives you've considered**
I haven't found an alternative, I've just re-entered the key each time the Docker container is restarted.

**Additional context**
I'm running Ollama Web UI in a Docker container on Windows (WSL2).

**Comment by justinh-rahb** [comment]
You can set a container environment variable by adding `-e OPENAI_API_KEY=your_api_key` to your `docker run` command, or adding another line to the environment section of the ollama-webui service in your Docker Compose file, depending how your launched it.

**Comment by mtompkins** [comment]
It may be worth considering moving the OpenAI implementation / API key to the user level as this bears a cost. That way the server "owner" wouldn't have to worry about users and their usage on the paid API.

**Comment by justinh-rahb** [comment]
> It may be worth considering moving the OpenAI implementation / API key to the user level as this bears a cost. That way the server "owner" wouldn't have to worry about users and their usage on the paid API.

@mtompkins This was the previous implementation, it was moved from client-side to backend in #381
