### ISSUE TITLE
Document Upload: Something went wrong :/ Error loading .

### ISSUE THREAD

**Issue by vexersa** [ollama-webui/ollama-webui#550]
# Bug Report

## Description

**Bug Summary:**
Uploading a document ( in this case a .csv) results in the error: 
Something went wrong :/
Error loading .

**Steps to Reproduce:**
Navigate to documents, attempt to upload a file. 

**Expected Behavior:**
File uploads. 

**Actual Behavior:**
Something went wrong :/
Error loading .

## Environment

Win11, Chrome
Ollama in WSL
Ollama-WebUI Docker

## Reproduction Details

**Confirmation:**

- [X ] I have read and followed all the instructions provided in the README.md.
- [X ] I have reviewed the troubleshooting.md document.
- [ X] I have included the browser console logs.
- [ X] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
![image](https://github.com/ollama-webui/ollama-webui/assets/7994227/377a4741-a76f-4cfd-abf8-d3beb9f84a84)

## Installation Method
Docker

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! csv file import should just work out of the box, could you share the csv file here with us?

**Comment by anzellai** [comment]
@vexersa if you look at the error carefully you can see that it seems it picked up the file mimetype as "excel's csv", I'm guessing there are some quote chars or linebreaks in your CSV.

Could you try either opening that CSV with Excel again or other software and saving as CSV again?

Excel's CSV and our usual "plain" CSV sometimes has differences in quote chars and linebreaks.

**Comment by Marclass** [comment]
@vexersa There's a soft limit for file sizes dictated by the RAM your environment has since the RAG parser loads the entire file into memory at once. How large is the file and how much ram does your docker host have?

Can you open the csv in notepad and see if there are is any excel meta data in the beginning of the file? If it's a plain CSV the file type should be "text/csv"

**Comment by Marclass** [comment]
I was able to make a plaintext csv file that gets flagged as application/vnd.ms-excel, but I haven't had any problems with it getting parsed since the back end goes off of the file extension. The uploaded files are also stored on the docker host, so if they don't have enough disk space it could cause problems too.

I made a PR #554 that adds excel parsers, so you may be able to save it as an xlsx file and get it imported that way. The excel parsers are really slow though.

**Comment by vexersa** [comment]
> @vexersa There's a soft limit for file sizes dictated by the RAM your environment has since the RAG parser loads the entire file into memory at once. How large is the file and how much ram does your docker host have?
> 
> Can you open the csv in notepad and see if there are is any excel meta data in the beginning of the file? If it's a plain CSV the file type should be "text/csv"

The Docker host has ~31GB available to it. The CSV is 24MB, but I've tested it with smaller .csvs of ~7MB. I don't think there is a disk space problem. 

I've opened the file and don't see any excel meta data. 😕

**Comment by vexersa** [comment]
> I was able to make a plaintext csv file that gets flagged as application/vnd.ms-excel, but I haven't had any problems with it getting parsed since the back end goes off of the file extension. The uploaded files are also stored on the docker host, so if they don't have enough disk space it could cause problems too.
> 
> I made a PR #554 that adds excel parsers, so you may be able to save it as an xlsx file and get it imported that way. The excel parsers are really slow though.

I think there should be enough space, I haven't specified a limit in Docker Desktop but there's around 50GB free on the drive itself...

I can try the Excel parser PR, thanks!

Is there a list of file extension compatibilities? 
Can we use something like vector DB's? 

Thanks for the help!

**Comment by vexersa** [comment]
Update: 
So interestingly, if I upload the csv to Google Sheets and export it as a csv, it imports...

**Comment by tjbck** [comment]
The problem seems to have been some sort of encoding issue, I'll close this issue and merge the suggested PR above, Thanks!

**Comment by max5800** [comment]
I'm on Version v0.1.115 and still have Issues Importing CSV Files. 
Any Suggestions where to start trooubleshooting?

**Comment by justinh-rahb** [comment]
> I'm on Version v0.1.115 and still have issues importing CSV files. Any suggestions where to start troubleshooting?

3 releases behind. Try updating.

**Comment by isidoroDiegoNeves** [comment]
I did the samething and worked here if someone have the same problem:

So interestingly, if I upload the csv to Google Sheets and export it as a csv, it imports...

**Comment by max5800** [comment]
> > I'm on Version v0.1.115 and still have issues importing CSV files. Any suggestions where to start troubleshooting?
> 
> 
> 
> 3 releases behind. Try updating.

Thanks but updating wasn't necessary, the solution was using a correctly formatted csv 🤝
