### ISSUE TITLE
Search acts weird

### ISSUE THREAD

**Issue by jnkstr** [ollama-webui/ollama-webui#556]
# Bug Report
Sometimes the search works but most of the time it shows nothing.

**Steps to Reproduce:**
I am testing the newest version with docker

**Expected Behavior:**
Search should work

**Actual Behavior:**
Sometimes the search works but most of the time it shows nothing.

## Environment

- **Operating System:** Windows 11
- **Browser (if applicable):** Chrome

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [ x] I have reviewed the troubleshooting.md document.
- [x ] I have included the browser console logs.
- [x ] I have included the Docker container logs.

## Logs and Screenshots

https://github.com/ollama-webui/ollama-webui/assets/69747628/41a36e6e-1d45-49d5-98f3-ba52b2bea8e1

## Installation Method

Docker Compose

**Comment by hammeiam** [comment]
They lowercase the chat titles but not the search term when searching. This should be fixed, but it'll work if you only use lowercase when searching.
https://github.com/ollama-webui/ollama-webui/blob/b6d9cf3bc8394098b09af27f1a5b431f9dadc423/src/lib/components/layout/Sidebar.svelte#L323
