### ISSUE TITLE
feat: Organize chats in folders

### ISSUE THREAD

**Issue by peperunas** [ollama-webui/ollama-webui#570]
**Is your feature request related to a problem? Please describe.**

I work by "contexts". I guess it would be great to organize conversations in folders or groups.

**Comment by justinh-rahb** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I work by "contexts". I guess it would be great to organize conversations in folders or groups.

@peperunas I believe the tagging feature should prove an adequate solution to this need:
<img width="500" alt="Screenshot 2024-01-25 at 11 28 25 AM" src="https://github.com/ollama-webui/ollama-webui/assets/52832301/b62b7635-5509-4a90-9941-9a2aa38b053b">

**Comment by peperunas** [comment]
Yep, sorry I did not see this!
