### ISSUE TITLE
feat: Task presets

### ISSUE THREAD

**Issue by peperunas** [ollama-webui/ollama-webui#572]
**Is your feature request related to a problem? Please describe.**

As of now, a way to speed up a task is by creating a prompt and then use it. Another way - quicker, in my opinion - is to create presets that bind together a model and a system prompt. In this way, the user can directly select the preset and start chatting right away.

This behaviour is implemented in this project [1], if that may help a comparison.

[1]: https://github.com/mckaywrigley/chatbot-ui

**Comment by justinh-rahb** [comment]
This is what the Modelfiles feature is for @peperunas

**Comment by peperunas** [comment]
Definitely, Modelfiles allow the feature, which is great! But, I don't see why we should make the backend churn out a new model file for every specific task. Why not let the UI handle that? It would make it a snap to switch between models.

Plus, tweaking a model file means messing with a bunch of settings. That gives you a lot of control, but it might be overdoing it for what we're trying to achieve here.

**Comment by justinh-rahb** [comment]
I find the modefile builder interface very easy to use, barely takes any time at all to create a new "task" as you say, right in the Ollama WebUI interface. What about the now-modifiable prompt templates on the new chat page? That was added in #548 Would this work for creating tasks that can be used with any model?

**Comment by tjbck** [comment]
I believe most of the feature you're suggesting is already in the modelfiles feature. I might fork this repo later down the line to be more LLM runner agnostic, and for that version the feature would be implemented the way you suggested. But for this project, the goal is to have a tight integration with Ollama, so I'll close this issue for now.

<img width="729" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/7b0a0ce3-c53d-402b-978b-ce00980d747f">
