### ISSUE TITLE
Integrate AutoGen into the UI

### ISSUE THREAD

**Issue by JasonPad19** [ollama-webui/ollama-webui#581]
**Is your feature request related to a problem? Please describe.**
AutoGen can be powered either by OpenAI endpoint or LM Studio endpoint. It will enable multi agent conversation per different roles(based on prompt).

**Describe the solution you'd like**
To enable multi agent conversation per AutoGen 
https://github.com/microsoft/autogen

**Describe alternatives you've considered**
XAgent is another alternative.
https://github.com/OpenBMB/XAgent

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! I'll close this issue for now, as at the moment integrating autogen directly seems like it's out of the scope of this project, but I'll think of ways we can have something similar with #463. Stay tuned!
