### ISSUE TITLE
WEBUI Model Selection does not persist firefox Linux

### ISSUE THREAD

**Issue by ganakee** [ollama-webui/ollama-webui#589]
[webui.log](https://github.com/ollama-webui/ollama-webui/files/14073374/webui.log)
# Bug Report
On each launch of the WEBUI, the WEBUI indicates that a model is not selected.

**Bug Summary:**
Each time WEBUI is opened, WEBUI seems to "forget" persistent information such as the models selected and the Prompt Suggestions.

**Steps to Reproduce:**

1. Open a new instance of WEBUI in a fresh browser (Firefox on Linux)
2. Navigate to WEBUI.
3. (Assumes loggedin). WEBUI displays.
4. If I try to submit a prompt or one of the Prompt Suggestions, I get a No model selected error.
5. I select the model from the top of the page.
6. I select Set default.
7. I also go into settings and set the model. Save.
8. Try prompt--works.
9. Close browser.
10. Reopen browser.
11. Navigate to WEBUI.
12. If I try to submit a prompt, error no model selected.
13. Go to Step 4 above.

**Expected Behavior:**
The settings should persist between sessions.

**Actual Behavior:**
The settings seem to disappear after a browser closure. I notice this with Set default model, the models settings page, and the Prompt Suggestions selections. I am logged in, but it seems like most of the core settings do not persist.

## Environment

- **Operating System:**
- POP OS 22.04
- 6.6.10-76060610-generic #202401051437~1704728131~22.04~24d69e2 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
- firefox 121.0.1 x64

## Logs and Screenshots

**Browser Console Logs:**
```
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved 4 ConduitsParent.sys.mjs:362
    _raceResponses resource://gre/modules/ConduitsParent.sys.mjs:362
NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart]
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.sys.mjs:1723
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.sys.mjs:1831
    BG_observe resource:///modules/BrowserGlue.sys.mjs:1060
    _delayedStartup chrome://browser/content/browser.js:2095
BrowserGlue.sys.mjs:1732:15
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.sys.mjs:1732
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.sys.mjs:1831
    BG_observe resource:///modules/BrowserGlue.sys.mjs:1060
    _delayedStartup chrome://browser/content/browser.js:2095
```

**Comment by tjbck** [comment]
Hi, I'm unable to reproduce the issue at all in all three of my machines using firefox (ubuntu, windows, macos). Could you verify that you can see the message toast when you click on set default like such:

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/ccc05fa5-feec-4106-8e70-f48c68b919ab)


Keep us updated, Thanks!

**Comment by ganakee** [comment]
If this happens to others, in my case, the issue was linked to my config.

I have ollama-webui running on Computer A mapped to port 3000.

I access ollama-webui on Computer B.

If Computer A was not up and running (with ollama-webui) BEFORE trying to access via Computer B, the error occurs. 

I have also seen this if Computer A is up and running but ollama-webui is restarted on Computer A, access by Computer B "forgets."

This is probably just my config. The solution is making sure ollama-webui is fully up and running (and no start/sstop) before trying to access it via Computer B.
