### ISSUE TITLE
feat: light mode support

### ISSUE THREAD

**Issue by TanvirOnGH** [ollama-webui/ollama-webui#59]
**Is your feature request related to a problem? Please describe.**
Currently, the UI only supports a default dark mode, which can be limiting for users who prefer a lighter interface or need to accommodate different lighting conditions. This feature request addresses the need for a more versatile user experience.

**Describe the solution you'd like**
I would like to request the addition of a light mode to the UI. This mode should provide a visually appealing, well-contrasted, and user-friendly interface with lighter color schemes. Users should be able to switch between dark and light modes based on their preferences.

**Describe alternatives you've considered**
One alternative to adding a light mode could be allowing users to customize the color scheme themselves. However, this could be more complex to implement and might lead to inconsistencies in the UI. Another alternative could be providing predefined themes, but it might not cater to all user preferences.

**Additional context**
As technology advances, users have come to expect more control over their user interface, including the ability to choose between light and dark modes. Adding a light mode to the UI will enhance user accessibility and satisfaction. It's also in line with current UI/UX best practices and can be a valuable addition for users who prefer a lighter, more vibrant design.

**Comment by tjbck** [comment]
Hi, Light mode support has been added with #64. Thanks!
