### ISSUE TITLE
There seems to be a problem in the admin interface element for users.

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#595]
![image](https://github.com/ollama-webui/ollama-webui/assets/23272429/45396863-5c6e-418a-a640-335673013d20)

I'm using the latest chrome on Ubuntu 22.04. It's also the same in my other computers. There's not much space.

**Comment by tjbck** [comment]
Hi, I'll change the design a bit but you should still be able to scroll horizontally, Thanks!

**Comment by oliverbob** [comment]
Ok.
