### ISSUE TITLE
feat: changing user profile image

### ISSUE THREAD

**Issue by TanvirOnGH** [ollama-webui/ollama-webui#61]
**Is your feature request related to a problem? Please describe.**
Currently, it lacks the functionality for users to customize their avatars or profile images. This limitation restricts personalization and user engagement, as avatars can be a key element of user identity and expression.

**Describe the solution you'd like**
I propose adding a feature that allows users to change their avatars or profile images within the interface. Users should be able to upload, select, or edit their avatars, giving them more control over their visual representation.

**Describe alternatives you've considered**
An alternative to this feature would be to rely solely on external platforms for profile image management, but this could lead to inconsistencies in user experience and may raise privacy concerns.

**Additional context**
User avatars or profile images can play a significant role in enhancing the user experience and creating a sense of identity within the chatbot community. Allowing users to change their avatars directly within the webui not only provides a personalized touch but also makes the it more engaging and user-centric.

**Comment by TanvirOnGH** [comment]
And even the ability to change the bot's avatar/profile image as well? being able to modify the bot's avatar or profile image can help in making it more understandable which models the responses are coming from or have originated.

**Comment by tjbck** [comment]
Hi, in the upcoming update, users will be able to update the profile image by providing their gravatar id.

Providing a feature to update the Ollama profile image doesn't seem like something I'd be able to implement in the near future as I would be focusing on adding more practical features to the web ui. However, if you manage to implement a good solution to update Ollama profile image, PR is always welcome. Thanks.

**Comment by tjbck** [comment]
Hi, The feature has just been implemented with #63. Thanks!

**Comment by tjbck** [comment]
You can now update your profile image by going to Settings>Addons and adding your gravatar email.
