### ISSUE TITLE
bug: chat history paused tip overlaps with menu items

### ISSUE THREAD

**Issue by adan89lion** [ollama-webui/ollama-webui#611]
# Bug Report

## Description

**Bug Summary:**
When chat history is disabled, the tip message about the said matter blocks the user menu.

**Steps to Reproduce:**
1. Turn off chat history in settings
2. Click on the bottom-right user menu
3. The menu is covered by the warning "Chat History is off for this browser"

**Expected Behavior:**
The user menu is covered

**Actual Behavior:**
The user menu should not be covered

## Environment

- **Operating System:** Tested on Android (OneUI 6.0), iOS 17.3 and macOS 14.3
- **Browser (if applicable):** Tested on Chrome 121.0.6167.139 (Official Build), Safari 17.3

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots
**Screenshots (if applicable):**
![image](https://github.com/ollama-webui/ollama-webui/assets/6585644/96b73bbb-7cbe-43d1-8be0-d02421e65d9a)
> Chat history enabled, user menu is visible.

![image](https://github.com/ollama-webui/ollama-webui/assets/6585644/04126fa9-33dc-43f2-b19e-24935f7263d2)
> Chat history disabled, user menu is covered.

## Installation Method

Install via Docker.

## Additional Information

N/A

## Note

N/A

**Comment by tjbck** [comment]
Hi, this is the intended behaviour! You can check ChatGPT has the same behaviour as well, Thanks!

**Comment by adan89lion** [comment]
Hi @tjbck,

I think ChatGPT does not have this behavior. I can still access my user menu (Settings, Help & FAQ, Logout, etc.) when the chat history is off.

![Screenshot 2024-02-02 at 04 05 27@2x](https://github.com/ollama-webui/ollama-webui/assets/6585644/27fdf4c6-a7d1-46f9-9047-fc95f5fe2199)

However, ollama-webui blocks the access to Admin Panel, Settings and Sign Out options when chat history is turned off.

**Comment by tjbck** [comment]
Oops, Taking a look!
