### ISSUE TITLE
feat: TTS automatic playback 

### ISSUE THREAD

**Issue by lainedfles** [ollama-webui/ollama-webui#620]
**Describe the solution you'd like**
A TTS automatic playback toggle would be very useful for a hands free experience.

**Comment by horiacristescu** [comment]
Yes, I second this. But also allow setting the voice speed.

**Comment by dkedinger** [comment]
Would love this as well. Trying to figure out a way to get it to automatically speak responses right now.

**Comment by lainedfles** [comment]
Thanks!
