### ISSUE TITLE
Multi modal support?

### ISSUE THREAD

**Issue by prologic** [ollama-webui/ollama-webui#631]
Are we able to add Multi modal support? Ollama now supports this and it would be great to see it added to this very lovely UI I've just come across and started using 🙏 It would be great to be able to a) answer questions asked about images added to "documents" and b) generate new images from prompts.

**Comment by tjbck** [comment]
Hi, feature a) has implemented a long time ago! you should just be able to drag and drop images to your chat input, make sure to use multimodal models like llava. As for the feature b), generating images is not within the scopes of multimodal models and Ollama does not support diffusion models and only supports LLMs afaik, but we'll consider adding it in the future (maybe via stable-diffusion-webui apis). Thanks!

**Comment by prologic** [comment]
Thanks I realized the same after I posted this! Sorry 🙏
