### ISSUE TITLE
Cannot disable titles

### ISSUE THREAD

**Issue by robertvazan** [ollama-webui/ollama-webui#635]
# Bug Report

## Description

**Bug Summary:**
Auto-generated titles cannot be disabled. Turning them off in settings has no effect.

**Steps to Reproduce:**
Go to settings, Add-ons tab, and set "Title Auto-Generation" to off. Start a new chat.

**Expected Behavior:**
The new chat should have default title since auto-generated titles are disabled.

**Actual Behavior:**
The new chat has a title that summarizes the prompt using LLM, ignoring settings.

## Additional Information

I can provide more data if you cannot reproduce this.

**Comment by tjbck** [comment]
If you turn off the title auto generation setting, the title will be set to the first prompt. Could you verify that that's not the case?

**Comment by robertvazan** [comment]
You are right. My bad. Sorry for the noise.
