### ISSUE TITLE
Apply system prompt and parameter overrides only to public models

### ISSUE THREAD

**Issue by robertvazan** [ollama-webui/ollama-webui#639]
**Is your feature request related to a problem? Please describe.**
Custom models usually have crafted system prompt and parameters as their main feature. Overriding them with global settings completely kills utility of custom models. It is also very confusing.

**Describe the solution you'd like**
Apply global settings (system prompt, parameters) only to the public models. Alternatively, have a checkbox in settings that says "Use for custom models too" (off by default), but that would require investing some thought into UI design, because it would have to apply to both system prompt and parameters, which are on separate tabs in settings.

**Describe alternatives you've considered**
For now, I have moved my main system prompt into a custom model and I am keeping system prompt in settings clear, so that it does not interfere with custom models. Ditto for parameters.

**Comment by tjbck** [comment]
I'll close this issue for now, as this won't be fixed unless we move away completely from Ollama.

**Comment by robertvazan** [comment]
Why would this require moving away from ollama? What does it even mean to move away from ollama? Isn't it WebUI that applies changes to system prompt and parameters for custom models? Isn't WebUI aware of whether it is using public or custom model? What prevents it from applying changes only to public models?
