### ISSUE TITLE
feat: bulk document upload

### ISSUE THREAD

**Issue by vrdeeznuts** [ollama-webui/ollama-webui#655]
**Is your feature request related to a problem? Please describe.**
I've seen a few issues relating to this (e.g., #531 and #533), and they were closed. However, after running ollama-webui and going to the My Documents page, when I click the + button to add documents, I have to add one document at a time. It gets cumbersome when I want to test RAG with a large folder of documents (as well as sub-folders with more documents). To be clear, this is unrelated to tagging documents. This problem also occurs when I try to drag and drop multiple documents at the same time. Only the first document gets uploaded.

**Describe the solution you'd like**
Enable bulk document upload via the + button as well as bulk document upload via drag and drop.

**Describe alternatives you've considered**
An alternative could be to provide a path to the directory containing documents when using the docker run ... command.

**Additional context**

**Comment by vrdeeznuts** [comment]
Also, apologies if that sounded rude or demanding. I am grateful for the work you've done to make everything run exceptionally well. Thank you!

**Comment by echzhai** [comment]
do you know if there is api, we could write a script to upload the files in a for loop? this can be a workaround.

@app.post("/doc")
def store_doc(

**Comment by echzhai** [comment]
@tjbck I think still if we could have an api that is better, for instance, if we want to upload 1000 files, and at the same time, we could tag these 1000 files.
if we do the tag later from webui, how could we tag 1000 files?

**Comment by nickjuntilla** [comment]
So I guess people just close these issues without addressing them? There is still no bulk document uploading. This issue was closed referencing a feature regarding a comment and bulk tagging.

**Comment by justinh-rahb** [comment]
This feature has existed for months. What's the issue?

**Comment by limingchina** [comment]
For me, selecting multiple files is working. However, I can't just drag a root directory so that all the files inside the directory got uploaded.
