### ISSUE TITLE
how to upload several files to my Documents? currently, I can only upload one by one, that's very inefficient.

### ISSUE THREAD

**Issue by echzhai** [ollama-webui/ollama-webui#657]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tjbck** [comment]
duplicate #655

**Comment by vrdeeznuts** [comment]
https://github.com/ollama-webui/ollama-webui/issues/651#issuecomment-1932186418
