### ISSUE TITLE
Ollama server inaccessible when requested from different network

### ISSUE THREAD

**Issue by Notarin** [ollama-webui/ollama-webui#67]
When hosting ollama on host1, and ollama-webui on host1, and attempting to access via host2 on a seperate network, the webui will refuse to connect to ollama, while working on host1.

**To Reproduce**
 - Install & Run Ollama
 - Install & Run Ollama WebUI
 - Port Forward
 - Attempt to access from any client other than the locally on server
It would be expected to function appropriately, however it for whatever reason pretends as if it cannot connect to the Ollama server, despite working just fine locally. Even if you port forward Ollama and point it to the public Ollama endpoint (verified) it will *still* not work whatsoever.

![image](https://github.com/ollama-webui/ollama-webui/assets/25104390/22aa3a27-5694-485a-b95d-976b03bbafc9)
![image](https://github.com/ollama-webui/ollama-webui/assets/25104390/191057ad-3e39-40ef-96b2-c71b2b6dd9bd)

**Server:**
 - OS: Arch Linux
 - Version: v1.0.0-alpha

**Client:**
 - OS: Windows 11
 - Browser: Chrome Developer Channel

**Comment by tjbck** [comment]
Hi, most likely a CORS problem. Were you able to check everything outlined in the troubleshooting section in readme.md? If you did and still experiencing the same issue, it would be helpful if you could provide a console log from your browser's developer tool. Thanks.

**Comment by Notarin** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25104390/dcdccb7c-f1d2-4aea-8e84-163e78d25455)
strange, it appears to be not obeying the provided parameter

**Comment by Notarin** [comment]
changing the default in the env file appears to have the expected effect.
I was under the false assumption that the requests were run server side, and was testing the server url via the settings menu.

**Comment by Notarin** [comment]
the only issue now is that setting the url via the settings menu is not working, should i rename this issue or make a new one?

**Comment by tjbck** [comment]
#70 should fix the issue. Please try again by building from the latest commit and let me know how it goes, Thanks!
