### ISSUE TITLE
feat: option to disable users from deleting their chat history

### ISSUE THREAD

**Issue by tbendien** [ollama-webui/ollama-webui#681]
As the Ollama Web UI sysadmin I need to be able to download chat history from all users and also block users from deleting their chat history.

**Describe the solution you'd like**
1. Enable the sysadmin to download use chat history on a per user basis for a given time range (up to the first day they used the OWUI app).
2. Block end users from deleting chat history
3. Ability to connect an S3 object storage bucket to OWUI so that chat history can be pushed into object storage vs  being stored on the local host.

**Describe alternatives you've considered**
Bionic GPT has this capability by connecting to it's local postgres database which has access logs and chat history logs.
I'd like to do the same thing with OWUI.

**Additional context**
I need this capability for chat history security and compliance audit use cases.

**Comment by tbendien** [comment]
Thanks @justinh-rahb - I am looking to use OWUI in High Schools with minors, so we have Legal compliance requirements that need us to be able to run reports on user activity. We can't have the kids using the tool and then deleting harmful chat history. So that's why we need the feature to block deletion of chats by end users - safety..

**Comment by justinh-rahb** [comment]
> Thanks @justinh-rahb - I am looking to use OWUI in High Schools with minors, so we have Legal compliance requirements that need us to be able to run reports on user activity. We can't have the kids using the tool and then deleting harmful chat history. So that's why we need the feature to block deletion of chats by end users - safety..

Absolutely, I believe almost any scenario where an admin would want a way to download the history in bulk would likely also require that it not be removeable by users. At the moment, fine-grained access controls are still a *planned* feature as opposed to *implemented*, please see related issue #446

**Comment by tjbck** [comment]
I'll narrow down the scope of this feature request to just  "blocking users with "user" role from deleting chat history". I don't plan on implementing the first and third requests in the near future, as they seem like very niche use cases. Feel free to create a separate issue/PR for the two.

**Comment by explorigin** [comment]
What is "delete" is just a flag in the database. Only show "not deleted" chats.

**Comment by explorigin** [comment]
Another future feature for this scenario would be an audit log. Delete could mean "remove from db" so long as it got dumped to the audit log.

**Comment by tbendien** [comment]
@tjbck @justinh-rahb is there any chance that you could implement the "blocking users with "user" role from deleting chat history" feature by end of this week? I am planning a demo next week and would be great if users are prevented from deleting chats by then. Thanks for the great project!!!

**Comment by tjbck** [comment]
@tbendien You can now toggle the setting from Admin Panel > Admin Settings > Users, let me know if you encounter any issues!

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/0db808c5-433d-4313-bcc8-e020c661ecba)
