### ISSUE TITLE
Please provide simple QuickStart install guide for Ubuntu from clean OS install

### ISSUE THREAD

**Issue by tbendien** [ollama-webui/ollama-webui#683]
# Bug Report

## Description
I have tried doing a new install of OWUI on my host with a NVIDIA GPU with a clean new install of Ubuntu and just can't get the web ui to connect to the local Ollama. I see from the forums that may people are having issues with the install.

The sad thing is that I got it running on this host before but I did not document my steps, now after several hours I still can't get it to work.

**Bug Summary:**
Getting Ollama server connection error.
There are no clear step by step instructions on doing a new install on a fresh Ubuntu host.

**Steps to Reproduce:**
Trying to follow the instructions.

**Expected Behavior:**
I would love to have a simple docker pull command to fully install Ollama and Ollama Web UI in one command.
I was hoping that the git clone and the single command below would do it...

**Actual Behavior:**
Can't get OWUI running. 

## Environment
Ubuntu 22.04 NVIDIA GPU

## Reproduction Details

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.

## Installation Method
git cloned the repo
ran:

docker build -t ollama-webui .
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v ollama-webui:/app/backend/data --name ollama-webui --restart always ollama-webui

Also tried installing Ollama locally, and it ran fine at the CLI with GPU.

**Comment by tjbck** [comment]
Duplicate #432, Please check out our troubleshooting guide as well.

**Comment by justinh-rahb** [comment]
Only command needed if you have already installed Ollama and verified with CLI:
```bash
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -e OLLAMA_API_BASE_URL=http://host.docker.internal:11434/api -v ollama-webui:/app/backend/data --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main
```

**Comment by tbendien** [comment]
@justinh-rahb I would like to ask if I may hire you to help me get this installation done. I am missing something and have to get this working.

**Comment by justinh-rahb** [comment]
> @justinh-rahb I would like to ask if I may hire you to help me get this installation done. I am missing something and have to get this working.

Sorry, I've got a dayjob, and this wouldn't feel right to me since the author of this project accepts sponsorships including tiers that come with support.
