### ISSUE TITLE
Bug: When restarting server some options are lost from config

### ISSUE THREAD

**Issue by horiacristescu** [ollama-webui/ollama-webui#684]
# Bug Report
When I restart the docker some of my settings disappear, such as the OpenAI key

**Steps to Reproduce:**
```
docker run -p 3000:8080 --add-host=host.docker.internal:host-gateway -v ollama-webui:/app/backend/data ghcr.io/ollama-webui/ollama-webui:main
```
## Environment

- **Operating System:** Ubuntu 18.04

**Comment by tjbck** [comment]
Documentation issue, they use environment variables. Let's continue our discussion here: #432

Sidenote, I'm currently extremely busy with day job at the moment so if anyone could get the rolling for the documentation, I'd greatly appreciate it, Thanks!
