### ISSUE TITLE
Uploading documents connects to external web services such as an AWS ELB?

### ISSUE THREAD

**Issue by prologic** [ollama-webui/ollama-webui#687]
# Bug Report

## Description

**Bug Summary:**

I tried to upload a document to my locally hosted instance of Ollama Web UI and to my horror I discovered that the Docker container (running Ollaba Web UI) wanted to connect to an AWS ELB?! Naturally I blocked this connection (thanks to LittleSnitch). Then it wanted to connect to another external services, some packages (didn't capture it).

**Steps to Reproduce:**

- Install a filtering/logging firewall like LittleSnitch
- Upload a document
- Observe external connections made

**Expected Behavior:**

I don't know wtf this is _trying_ to do, but I **really** DO NOT expect a locally hosted instance of anything to be connecting externally to some 3rd-party services (_within reason of course_). This is absurd.

At the very least, could someone please explain why this is happening and what this is even used for? Maybe it's legit and required for some part of the "Upload Document" user journey to work?

**Actual Behavior:**

I expect locally hosted software to **NOT** connect to external services. The whole point of using Ollama in the first place is to run local LLM models 😅

## Environment

Not really relevant. But Docker container on a Mac.

PS: Your Issue template is too long. Please simplify it, I don't generally have and time and patience to fill out everything asked, especially of a vision impaired person. It also takes some of the "human"(ity) out of helping to contribute to "better" open source software.

**Comment by prologic** [comment]
FWIW blocking the two connections didn't appear to affect the functionality of Uploading a document. I was later able to select it and use it in context with `#`, so I'm really confused as to why those connections are even necessary at all 🤔

**Comment by tjbck** [comment]
Hi, Thanks for reporting this issue. Could you verify that AWS ELB connection is 100% occurring from the webui-side? Our backend code do no contain any code that explicitly makes connection with AWS ELB, so my guess is the request is made from one of our dependency libraries. If you could narrow down what part of the code making the connection, that would be tremendously helpful, Thanks!

**Comment by prologic** [comment]
Yup makes sense! 

I'll try to narrow this down 👌 As you said, If you're not doing this explicitly in this codebase then I consider a sneaky supply chain type of thing 🤣

**Comment by prologic** [comment]
So here we go:

Text version(s):

```
Docker wants to connect to a046be49099ce4659abbcfa853797f20-5fd7cc9498e4883e.elb.ap-southeast-1.amazonaws.com on TCP port 443 (https)

Docker wants to connect to packages.unstructured.io on TCP port 443 (https)
```

Screenshots: 
<img width="678" alt="Screenshot 2024-02-10 at 11 12 24" src="https://github.com/ollama-webui/ollama-webui/assets/1290234/022dca20-690f-441e-a8df-7e29d76ae68c">
<img width="636" alt="Screenshot 2024-02-10 at 11 12 55" src="https://github.com/ollama-webui/ollama-webui/assets/1290234/514b7ae1-3f69-4b79-8741-8765b6db8d57">

**Comment by prologic** [comment]
Note that this is the container itself _trying_ to do this, so something to do with the backend.

**Comment by prologic** [comment]
Doing a [search](https://github.com/search?q=%22packages.unstructured.io%22&ref=opensearch&type=code) for the 2nd connection yield this: 

https://github.com/Unstructured-IO/unstructured/blob/d11c70cf83fdb8a08fed2cf01c6c0bd114d817df/unstructured/utils.py#L287-L319

Are we using this in the backenda anywhere? 🤔

**Comment by tjbck** [comment]
Here's a list of our suspects:

```
langchain
langchain-community
chromadb
sentence_transformers
pypdf
docx2txt
unstructured
markdown
pypandoc
pandas
openpyxl
pyxlsb
xlrd
```

**Comment by prologic** [comment]
We are:

https://github.com/ollama-webui/ollama-webui/blob/cb5520c519dde81bfe08ce358753ab7f11417f97/backend/requirements.txt#L25

Why does it need to connect to an external service? 🤔

**Comment by prologic** [comment]
I can't figure out this random ELB though, might need some help figuring that one out. But at least we have some culprits now.... The question is, what do we do about it? Blocking both doesn't adversely affect Ollama Web UI in any way that I can tell hmmm

**Comment by prologic** [comment]
Oh wow!

```python
def scarf_analytics():
...
`

If this library is sending analytics, that's disgusting 😱

**Comment by tjbck** [comment]
`UnstructuredMarkdownLoader` seems to be the culprit, investigating more.

**Comment by prologic** [comment]
>Open source libraries and APIs to build custom preprocessing pipelines for labeling, training, or production machine learning pipelines.
>
> [www.unstructured.io/](https://www.unstructured.io/)

I have half a mind to go yell at this company and ask them to please explain themselves 🤣 Shame on them!

**Comment by tjbck** [comment]
Just reviewed the code, I reckon setting `DO_NOT_TRACK` env var to `True` will stop the telemetry, could you try testing it?

**Comment by prologic** [comment]
Love it! Let's do it, happy to test the fix 👌

**Comment by prologic** [comment]
And thank you for responding to this so quickly! When you're self hosting and insisting on doing things locally, you really don't expect your software to reach out to the internet without you knowing about it 😅

**Comment by prologic** [comment]
Some kudos I [posted](https://twtxt.net/twt/me3ac2a) for you 😅

**Comment by justinh-rahb** [comment]
Good find guys, ya that definitely not nice of them to do. Is there any disclosure from the libary anywhere?

**Comment by prologic** [comment]
> Good find guys, ya that definitely not nice of them to do. Is there any disclosure from the libary anywhere?

Are you suggesting we file a bug upstream too? It was a bit of a rude surprise to be honest 😅

**Comment by tjbck** [comment]
@justinh-rahb none I can find from their [readme](https://github.com/Unstructured-IO/unstructured) :/

**Comment by tjbck** [comment]
Added 
```
ENV SCARF_NO_ANALYTICS true
ENV DO_NOT_TRACK true
```
with #694, it should disable the telemetry. Please try it out and let me know!

**Comment by justinh-rahb** [comment]
With RAG being as hot as it is right now, I guess we shouldn't be surprised that some libary authors are cashing in on the user data flowing through their code.

**Comment by tjbck** [comment]
@prologic has the issue been resolved with the latest release?

**Comment by prologic** [comment]
I pulled the latest Docker image and restarted my local instance and so far so good 😊

**Comment by tjbck** [comment]
I'll close this issue for now, feel free to open new issues if you encounter any spywares from the dependency supply chain, thanks!

**Comment by aswani-ms** [comment]
Do you have an example code how to upload a document programatically through an api? is it possible
