### ISSUE TITLE
documents/create 500 Error

### ISSUE THREAD

**Issue by 7a6ac0** [ollama-webui/ollama-webui#700]
# Bug Report

## Description
Hi, when I upload files from the `Documents` tab, then I got the response code(500 Internal Server Error) after send a request of documents/create.
**Bug Summary:**
[Provide a brief but clear summary of the bug]
Upload a file from Documents tab, got a 500 error code.
**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]
1. Click the Documents tab
2. Click '+' button
3. Select a file to upload

**Expected Behavior:**
[Describe what you expected to happen.]
Upload file success
**Actual Behavior:**
[Describe what actually happened.]
Upload file failed, and get the response code (500 Error)
## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
macOS sonoma 14.2.1
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
Brave v1.62.156
## Reproduction Details

**Confirmation:**

- [v] I have read and followed all the instructions provided in the README.md.
- [v] I have reviewed the troubleshooting.md document.
- [v] I have included the browser console logs.
- [v] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]
```
text/plain
INFO:     192.168.215.1:59832 - "POST /rag/api/v1/doc HTTP/1.1" 200 OK
INFO:     192.168.215.1:59832 - "POST /api/v1/documents/create HTTP/1.1" 500 Internal Server Error
INFO:     192.168.215.1:59832 - "GET /api/v1/documents/ HTTP/1.1" 200 OK
```
**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]
<img width="585" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/9023212/2eb341bd-d167-458a-b001-140393ec1b05">

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]
Docker
## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
https://github.com/ollama-webui/ollama-webui/pull/701 should fix it! Please try out the latest version, and let me know if the issue persists!

**Comment by 7a6ac0** [comment]
It's work. Thanks.

**Comment by liubin595338764** [comment]
@tjbck 上传MD文档报错，上传txt文档是正常的
<img width="643" alt="image" src="https://github.com/open-webui/open-webui/assets/5274428/bcd24394-1497-4611-ae92-59bcd133e7ed">
