### ISSUE TITLE
Unable to approve pending users or delete users

### ISSUE THREAD

**Issue by jsaiko** [ollama-webui/ollama-webui#702]
# Bug Report

## Description

**Bug Summary:**
When clicking the user role to approve a user or the delete button to delete a user, an error occurs.

**Steps to Reproduce:**
Sign up with a new user other than admin account.  Try to enable account in admin portal.

**Expected Behavior:**
Clicking on the user role should enable the account.

**Actual Behavior:**
500 internal server error occurs.

## Environment

- **Operating System:**  Ubuntu 22.04
- **Browser (if applicable):** Chrome

## Reproduction Details

**Confirmation:**

- [ X] I have read and followed all the instructions provided in the README.md.
- [ X] I have reviewed the troubleshooting.md document.
- [ X] I have included the browser console logs.
- [ X] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**

POST http://XXXXXXXX:8080/api/v1/users/update/role 500 (Internal Server Error)
window.fetch @ start.6e21f321.js:1
bt @ 4.ea9424de.js:1
L @ 4.ea9424de.js:1
Ct.h @ 4.ea9424de.js:1
N @ 4.ea9424de.js:1
4.ea9424de.js:1 SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON

**Docker Container Logs:**

INFO:     172.17.0.1:48302 - "POST /api/v1/users/update/role HTTP/1.1" 500 Internal Server Error
INFO:     172.17.0.1:58496 - "POST /api/v1/users/update/role HTTP/1.1" 500 Internal Server Error
INFO:     172.17.0.1:58496 - "POST /api/v1/users/update/role HTTP/1.1" 500 Internal Server Error

**Screenshots (if applicable):**

![image](https://github.com/ollama-webui/ollama-webui/assets/68829025/0174d902-f8cd-41fd-a072-231110b3f07f)

## Installation Method

Docker

## Additional Information

None

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
https://github.com/ollama-webui/ollama-webui/pull/701/files should've fixed it! Please try out the latest version, and let me know if the issue persists!

**Comment by jsaiko** [comment]
Confirmed working.  Thanks!
