### ISSUE TITLE
User role for new user not changing in admin panel

### ISSUE THREAD

**Issue by gurgutan** [ollama-webui/ollama-webui#705]
# Bug Report

## Description

**Bug Summary:**
Can't change user role for new user in admin panel, and he stay pending status

**Steps to Reproduce:**
Clicked on the user role (not Admin) cell in the table to change a user's role

**Expected Behavior:**
Pending role change to approved

**Actual Behavior:**
nothing happened

## Environment

- **Operating System:** [Ubuntu 20.04]
- **Browser (if applicable):** [Firefox 122.0 (64-разрядный)]

## Reproduction Details

**Confirmation:**

- [ х] I have read and followed all the instructions provided in the README.md.
- [ х] I have reviewed the troubleshooting.md document.
- [ х] I have included the browser console logs.
- [ х] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
Request:
{"id":"b4ec8863-fe7b-4822-aedf-695587c914a7","role":"user"}

Response:
XHRPOST
http://localhost:8080/api/v1/users/update/role
[HTTP/1.1 500 Internal Server Error 4ms]

 

**Screenshots (if applicable):**
![log1 2024-02-11 11-20-35](https://github.com/ollama-webui/ollama-webui/assets/31627997/3927167b-a670-44e6-81cf-8a9e8c393b0e)

**Comment by tjbck** [comment]
https://github.com/ollama-webui/ollama-webui/pull/701 should've fixed it! Please try out the latest version, and let me know if the issue persists!

**Comment by mcantos89** [comment]
Hi, i need help for this issue, isn't possible change role
![Captura](https://github.com/open-webui/open-webui/assets/126183553/6a05a7df-0677-4a47-8102-c4c13ad1082a)

**Comment by justinh-rahb** [comment]
> v1.0.0-alpha.92

This version is ***ANCIENT***.

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/29a15231-d194-4479-8e9e-dd7dd8d4e388)

**Comment by mcantos89** [comment]
Thanks! I'm Lamer hahaha 
![image](https://github.com/open-webui/open-webui/assets/126183553/cba4b754-09f6-4d7b-b176-48cb3c3fcce2)

It's in a new version

**THANKS!**
