### ISSUE TITLE
feature request allow to set how many threads /processers are used

### ISSUE THREAD

**Issue by mhussaincov94** [ollama-webui/ollama-webui#710]
hi,
it would be great if there was the capability to be able to set how many threads/processers are used
for genneration of responces etc.
is this possible?
thank you for considdering my request

**Comment by tjbck** [comment]
Hi, thanks for the feature request. I'll close this issue as Ollama does no offer such API afaik, but I could be wrong. Feel free to leave a comment here and I'll reopen the issue!

**Comment by chamburr** [comment]
They do offer this feature with `num_thread`, which can be passed along with other parameters like temperature.

https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values
