### ISSUE TITLE
feat: hope to provide a widescreen display option

### ISSUE THREAD

**Issue by tisfeng** [ollama-webui/ollama-webui#711]
**Is your feature request related to a problem? Please describe.**

On my computer, there is so much white space on the right side of the chat screen that it can look odd, resulting in very little displayable content.

**Describe the solution you'd like**

Wish full use of screen space, instead of fixed showing part of the area.

**Describe alternatives you've considered**

If we don't modify the default chat width, perhaps we can provide an additional widescreen option to expand the chat display area on both sides, just like [KeepChatGPT](https://github.com/xcanwin/KeepChatGPT).

**Additional context**

### ollama-webui

<img width="1708" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25194972/4cceedb8-dd0f-49bb-9b80-21b0a517642e">

### [KeepChatGPT](https://github.com/xcanwin/KeepChatGPT)

<img width="1709" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25194972/65bf2077-ff8e-494a-8107-c6baaf7ab1bc">

**Comment by tjbck** [comment]
You can now toggle the fullscreen mode option from Settings > Interface!

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/d2324e4f-7b04-49e9-ab5d-47aa02e74539)

**Comment by tisfeng** [comment]
Great 😊

**Comment by tisfeng** [comment]
Please have a look, Full screen mode looks weird  https://github.com/ollama-webui/ollama-webui/issues/747
