### ISSUE TITLE
bug: whisper processing is not local?

### ISSUE THREAD

**Issue by jnkstr** [ollama-webui/ollama-webui#716]
# Bug Report

## Description

**Bug Summary:**
If you user whisper and turn of the internet connection it wont work.

**Steps to Reproduce:**
Turn off internet connection and try voice input with whisper.

**Expected Behavior:**
I don't know if this is as expected but in the settings its named "Whisper (Local)", so it should be working without internet since you can implement that with whisper.

**Actual Behavior:**
Does nothing, if you turn internet on and wait a few seconds the words you saind during offline time appear.

## Environment

- **Operating System:** [Windows 11]
- **Browser (if applicable):** [Chrome]

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [x ] I have reviewed the troubleshooting.md document.

**Comment by justinh-rahb** [comment]
The local Whisper mode does require internet at least for the first attempt to use it because it does not download the model until then. Try again now that you have and report back please.

**Comment by tjbck** [comment]
As @justinh-rahb mentioned, the bug you describe is the expected behaviour. Feel free to make a PR if you manage to find a way to embed the whisper model to the container image, Thanks!
