### ISSUE TITLE
User count limit to 50(?)

### ISSUE THREAD

**Issue by fwxfasp** [ollama-webui/ollama-webui#729]
**Is your feature request related to a problem? Please describe.**

I experience, that the 51st user who registers on the system is not visible in the admin user list and therefore can't be activated

**Describe the solution you'd like**
I'm not 100% sure, but after a quick search in the code, it seems that the user count is limited to 50 users
(apps/web/routers/users.py)

**Describe alternatives you've considered**
I wonder if or why that limit is required. Might be nice to make the value configurable and not hard-coded if possible

Would be great if you could help here.
Keep up the great work!

**Comment by tjbck** [comment]
Hi, Thanks for reporting this issue, I'll take a look in a bit.

**Comment by fwxfasp** [comment]
Thank you very much for the quick reply and fix!
I'll test asap (possibly not before next week) and report back.

**Comment by fwxfasp** [comment]
Hi there,
I can confirm the fix works as expected. Thank you very much! :)
