### ISSUE TITLE
Full Screen Mode looks weird

### ISSUE THREAD

**Issue by tisfeng** [ollama-webui/ollama-webui#747]
# Bug Report

## Description

**Bug Summary:**

Full screen mode looks weird with the sides obscured

<img width="1705" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25194972/a23efe30-fbec-41d3-b639-baf2ced69c12">

**Steps to Reproduce:**

Just turn on Full Screen Mode

## Environment

Apple M1 Pro, Chrome 121.0.6167.160

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Installation Method

Docker

**Comment by tjbck** [comment]
Hi, that is the expected layout. You can toggle the button on the sidebar to close it, and see all the messages without them being obscured by the sidebar, Thanks.

**Comment by justinh-rahb** [comment]
Sorry @tjbck I'm gonna have to be a stick in the mud here and say this behaviour of the styling has bugged me for a while, the content of the chat should be centered between the right edge of the sidebar and the right edge of the viewport, and reflow if the sidebar is closed, as our inspiration does it:
![Screenshot 2024-02-15 at 1 34 29 PM](https://github.com/ollama-webui/ollama-webui/assets/52832301/7a6b2b9a-a969-44c0-923e-71557ac062de)

And I'd say that should also fix this particular issue report too.

**Comment by tjbck** [comment]
@justinh-rahb I suppose the reason why it looks the way it does now is because I wanted the webui to have a consistent layout with the mobile viewport, but I'll take a look and see what can be done!

**Comment by tjbck** [comment]
@tisfeng #751 changes the layout behaviour to what you've described in the prior issue post, let me know if you encounter any issues!

**Comment by tisfeng** [comment]
So good, thank you!
