### ISSUE TITLE
Output limited to a very narrow collumn - text squashed and screen realestate wasted

### ISSUE THREAD

**Issue by sammcj** [ollama-webui/ollama-webui#750]
# Bug Report

## Description

**Bug Summary:**

The application seems to limit the width of the chat conversation to a very narrow column.

This makes for excessive scrolling and makes reading code difficult.

**Steps to Reproduce:**

It appears be be hard coded like this so I think everyone would experience it.

**Expected Behaviour:**

The width of the conversation area to scale horizontally to the available display size + a little padding.

For example, perhaps it could always be about 80% of the available space between the side panel the the scrollbar?

Otherwise - an option to set the maximum width in settings would be great.

**Actual Behaviour:**

Text is squashed into a tiny little column in the centre of your browser window.

This might be OK for a mobile device but is very hard to work with on a standard 4k screen.

## Environment

- Firefox 122.0.1
- macOS 14.3.1

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**

N/A (I think), but just let me know if you'd like me to provide any of the calculated CSS/HTML and I'll add it.

**Docker Container Logs:**

N/A (no errors)

**Screenshots (if applicable):**

<img width="3359" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/862951/68a43831-0c07-42f3-a830-72a746fec992">

<img width="383" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/862951/08eafb5b-8101-4ef5-9031-39bdd09fa647">

## Installation Method

Docker

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Duplicate issue: #711

Fixed in: PR #744 

If I could humbly suggest, please review past issues or discussions in the future before opening new ones, though I do commend you for giving an otherwise detailed report.

**Comment by sammcj** [comment]
I did search through issues first.

Fullscreen mode doesn't fix it - that seems to be the complete other end of the spectrum where it uses all of your browser which is overkill unless I guess you're running it full screen on a dashboard maybe?

<img width="3336" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/862951/a44ed482-793b-4fcc-b0b3-d3be9fa440a3">

**Comment by justinh-rahb** [comment]
> Fullscreen mode doesn't fix it (and it seems to be a bit broken as well).
>
> What I'm proposing here is a responsive or at least configurable design.
>

Fair, I agree fully on both of these, perhaps a refac of the issue title and expected outcome could be agreed on as well?

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/4c21c66a-91b0-482c-b655-56e9d1833437)

Screenshot of WIP

**Comment by sammcj** [comment]
Yeah sorry if I didn't explain it very well the first time - sometimes it's hard to describe in words 😅

**Comment by sammcj** [comment]
What resolution / scaling is that at @tjbck?

**Comment by justinh-rahb** [comment]
Oh Tim, my OCD would hug you but my ASD doesn't do hugs 🥰

**Comment by justinh-rahb** [comment]
My apologies @sammcj, with more context of your intention, your issue report is bang on. And now @tjbck has something to tag with his incoming PR 👍

**Comment by tjbck** [comment]
@sammcj not entirely sure, but using a 33" monitor with macos!

**Comment by justinh-rahb** [comment]
![f8e3714ed0d4a19b65ebe61006ac9bde](https://github.com/ollama-webui/ollama-webui/assets/52832301/ec48e561-14de-41dd-b461-6d8613035e0c)

**Comment by sammcj** [comment]
woop woop, thanks folks - that was incredibly fast turnaround 😄 ❤️
