### ISSUE TITLE
UI - model list dropdown darkmode display issue

### ISSUE THREAD

**Issue by gssdev-mb** [ollama-webui/ollama-webui#83]
When using darkmode,  the dropdown menu is displayed in white with barely legible grey text . This occurs on my windows 10 desktop for chrome, brave, and mozilla  firefox browsers. This also occurs on my linux mint laptop for brave but not for firefox.  Screenshot attached.  All browsers are using the most up to date versions.  I am accessing the web-ui remotely from an ubuntu linux server (22.04.3) running the ollama-webui docker . 

![ollama web ui - issue for github](https://github.com/ollama-webui/ollama-webui/assets/67763721/7b9e826b-6953-404c-89c8-1a00f2853b5e)

**Comment by tjbck** [comment]
Hi, Just merged #84 to main, which should fix your issue. Let me know if your issue still persists. Thanks!

**Comment by gssdev-mb** [comment]
Wow, thanks for the blazing speed response time! I removed the existing docker image and rebuilt again. I deleted the cache on my browsers and still had the same issue. Please let me know if I should be doing something else to see the fix. Thanks.

**Comment by tjbck** [comment]
Hi, I was able to test it on my windows machine and it seems to have fixed the issue. I'll test it out on my ubuntu machine soon and let you know. Thanks!

**Comment by tjbck** [comment]
![Screenshot from 2023-11-09 12-01-04](https://github.com/ollama-webui/ollama-webui/assets/25473318/087c02a0-db18-4d8d-8719-2abe3b47741f)

It seems to be working fine on my ubuntu machine (tested with chrome), maybe try again with using incognito mode and see if it fixes the issue, which would mean that your browser cache has not been deleted entirely. Keep us updated, Thanks.

**Comment by gssdev-mb** [comment]
Are you running web-ui locally? My use case is ollama-web run on a linux server being accessed by a windows pc and linux laptop on the same network.  On the window PC the issue persists on all browsers even after deleting cache. On the linux mint laptop, only firefox UI dropdown text is legible (pic) . I also tried on a linx vm, accessing the server for the first time. Brave browser has the same behavior where where as the firefox browser displays a legible dark backgroung (pic). Chrome has the same behaviour as brave for both platforms.

So net net for me, only the linux firefox browser displays ledgible text on a dark background while using dark mode. 
![ollama web issue -screenshot linx mint vm mozilla](https://github.com/ollama-webui/ollama-webui/assets/67763721/5342fc21-796c-42f6-9555-fc791d75d05f)

**Comment by tjbck** [comment]
I can verify it worked over LAN for both windows and ubuntu machines, could you also make sure that you've built the docker container using the latest version (after git pull) of the ollama-webui? Keep us updated. Thanks.

**Comment by gssdev-mb** [comment]
Duhhh...I didn't do that. It works now. Thanks again for the fast feedback and fix.
