### ISSUE TITLE
No model listed when accessing web page from network.

### ISSUE THREAD

**Issue by lafintiger** [ollama-webui/ollama-webui#88]
**Describe the bug**
When connecting to the web page locally, webpage opens and Select a model shows the list of all models to choose from. When I access the web page from the network, the webpage opens up but no models list. 

**To Reproduce**
1. ollama-webui % npm run dev
2.   ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.254.55:5173/
  ➜  Network: http://192.168.254.54:5173/
  ➜  press h to show help

3. When I open the local webpage. webpage opens and models can be selected.
4. When I open the Network webpage, with either ip address, the web page opens but no model shows.
5. See error
![FullSizeRender](https://github.com/ollama-webui/ollama-webui/assets/13715976/ff2bee62-760d-499b-aef2-b626d88f80d5)

**Expected behavior**
I should see the full list of models

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.1
 - Browser Brave
 - Version 1.60

**Smartphone (please complete the following information):**

**Additional context**
 
Any guidance would be appreciated.

**Comment by tjbck** [comment]
Hi, were you able to follow all the instructions from https://github.com/ollama-webui/ollama-webui#accessing-ollama-web-interface-over-lan? Let me know it still causes an issue for you even after you have all the env variables correctly setup. Thanks!

**Comment by lafintiger** [comment]
I followed the steps again and this time it worked. Not sure what was different from the first few times I ran it and this time. If I figure out how to duplicate the error, I will let you know.  Thanks.
